medias = {
    "bah": ["cor des Alpes"],
    "bbb": ["saxhorn baryton", "saxtromba baryton"],
    "bbd": ["bombardone", "basse impériale"],
    "bbd": ["bombardone", "saxhorn basse"],
    "bbu": ["clairon", "bugle baryton"],
    "bbu": ["clairon", "bugleret"],
    "bbu": ["clairon", "cor buglèr"],
    "bbu": ["clairon", "cor bugleret"],
    "bco": ["cornet à pistons", "piston"],
    "bct": ["cornet à bouquin", "cornaboux"],
    "bdx": ["dublophone", "lyrophone"],
    "beu": ["euphonium", "baritone"],
    "beu": ["euphonium", "baryton en sib"],
    "beu": ["euphonium", "basse à pistons"],
    "beu": ["euphonium", "basse en sib"],
    "beu": ["euphonium", "basse impériale"],
    "bhh": ["cor de chasse", "huchet"],
    "bhh": ["cor de chasse", "trompe de chasse"],
    "bho": ["cor", "cor à piston"],
    "bho": ["cor", "cor d'harmonie"],
    "bho": ["cor", "cor naturel"],
    "bho": ["cor", "cor simple"],
    "bho": ["cor", "trompe"],
    "bht": ["buisine", "bousine"],
    "bht": ["buisine", "busine"],
    "bht": ["buisine", "buysine"],
    "bht": ["buisine", "buzine"],
    "bkb": ["bugle à clefs", "cor à clefs"],
    "bkb": ["bugle à clefs", "taille d'amour"],
    "bkb": ["bugle à clefs", "trompette à clefs"],
    "bol": ["cor d'olifant", "oliphant"],
    "bop": ["ophicleïde", "basse à clefs"],
    "bop": ["ophicleïde", "basse d'harmonie"],
    "bop": ["ophicleïde", "contrebasse d'harmonie"],
    "bop": ["ophicleïde", "serpentcleide"],
    "bop": ["ophicleïde", "tuba-dupré"],
    "bph": ["cornet de poste", "cornet de postillon"],
    "brh": ["cor russe"],
    "bse": ["serpent", "basse-cor"],
    "bse": ["serpent", "basse-trompette"],
    "bse": ["serpent", "basson russe"],
    "bse": ["serpent", "basson serpent"],
    "bse": ["serpent", "serpent d'église"],
    "bse": ["serpent", "serpent droit"],
    "bse": ["serpent", "serpent militaire"],
    "bse": ["serpent", "serpenton"],
    "bsh": ["chofar", "chophar"],
    "btb": ["trombone à coulisse", "sacqueboute"],
    "btb": ["trombone à coulisse", "saicqueboute"],
    "btb": ["trombone à coulisse", "saqueboute"],
    "btb": ["trombone à coulisse", "trompette saqueboute"],
    "btb": ["trombone", "sacqueboute"],
    "btb": ["trombone", "saicqueboute"],
    "btb": ["trombone", "saqueboute"],
    "btb": ["trombone", "trompette saqueboute"],
    "btr": ["trompette"],
    "btu": ["tuba"],
    "bun": ["cuivre"],
    "bun__y": ["cuivre - ethnique"],
    "bvb": ["bugle à pistons", "saxhorn"],
    "bvb": ["bugle à pistons", "sudrophone"],
    "bvba": ["petit bugle", "bugle soprano en Mib"],
    "bvba": ["petit bugle", "saxhorn sopranino"],
    "bvbb": ["bugle", "saxhorn soprano"],
    "bvbc": ["saxhorn alto", "alto en Mib"],
    "bvbc": ["saxhorn alto", "baryton aigu"],
    "bvbc": ["saxhorn alto", "bugle alto"],
    "bvbc": ["saxhorn alto", "clavicor"],
    "bvbc": ["saxhorn alto", "tenor cor"],
    "bvbc": ["saxhorn alto", "ténor en Mib"],
    "bvbd": ["saxhorn ténor", "baryton"],
    "bvbd": ["saxhorn ténor", "bugle ténor"],
    "bvbd": ["saxhorn ténor", "clavicor"],
    "bvbi": ["petit saxhorn suraigu"],
    "bzz": ["cuivre - autre"],
    "cch": ["choeur d'enfants", "chœur d'enfants"],
    "cme": ["choeur d'hommes", "chœur d'hommes"],
    "cmi": ["choeur mixte", "chœur mixte"],
    "cre": ["choeur parlé", "chœur parlé"],
    "cun": ["choeur", "chœur"],
    "cun__y": ["choeur - ethnique"],
    "cve": ["ensemble vocal"],
    "cwo": ["choeur de femmes", "chœur de femmes"],
    "czz": ["choeur - autre"],
    "eco": ["ordinateur", "ordinateur portable"],
    "eco": ["ordinateur", "processeur numérique"],
    "ecs": ["station informatique musicale"],
    "ect": ["bande réalisée par ordinateur, sons fixés"],
    "eea": ["dispositif électroacoustique"],
    "eli": ["dispositif électronique temps réel"],
    "ema": ["ondes Martenot"],
    "eme": ["méta-instrument"],
    "emu": ["dispositif multimédia"],
    "eos": ["oscillateur"],
    "esp": ["dispositif spatial"],
    "esy": ["synthétiseur"],
    "eta": ["bande magnétique"],
    "eth": ["thereminovox"],
    "eun": ["instrument électronique"],
    "ezz": ["instrument électronique - autre"],
    "kac": ["accordéon", "harmonieflûte"],
    "kba": ["bandonéon"],
    "kca": ["carillon", "jeu de timbres"],
    "kca": ["carillon", "timbres"],
    "kce": ["célesta", "adiaphone"],
    "kce": ["célesta", "céleste"],
    "kch": ["chordette"],
    "kcl": ["clavicorde", "épinette sourde"],
    "kcl": ["clavicorde", "manicorde"],
    "kcl": ["clavicorde", "manicordion"],
    "kco": ["clavecin organisé", "épinette organisée"],
    "kfp": ["pianoforte", "piano-forte"],
    "kgl": ["glockenspiel"],
    "khm": ["harmonium", "harmonicorde"],
    "khm": ["harmonium", "orgue américain"],
    "khm": ["harmonium", "orgue expressif"],
    "khm": ["harmonium", "piano-chanteur"],
    "khm": ["harmonium", "poïkilorgue"],
    "khm": ["harmonium", "séraphine"],
    "khp": ["clavecin", "clavecin brisé"],
    "khp": ["clavecin", "clavessin"],
    "kor": ["orgue", "orgue positif"],
    "kor": ["orgue", "orgues"],
    "kor__r": ["orgue électrique", "orgue hammond"],
    "kpf": ["piano", "luthéal"],
    "kpf": ["piano", "piano cycloide"],
    "kpf": ["piano", "piano droit"],
    "kpf": ["piano", "piano elliptique"],
    "kpf": ["piano", "piano-luthéal"],
    "kpf__r": ["piano électrique"],
    "kpf__s": ["piano électronique"],
    "kps": ["clavier à cordes pincées"],
    "kun": ["clavier", "instrument à clavier"],
    "kun__y": ["clavier - ethnique"],
    "kzz": ["clavier - autre"],
    "mah": ["harpe éolienne", "aéro-clavicorde"],
    "mah": ["harpe éolienne", "anémocorde"],
    "mah": ["harpe éolienne", "piano éolien"],
    "mbo": ["orgue à manivelle", "orgue de barbarie"],
    "mbr": ["rhombe", "planchette ronflante"],
    "mbs": ["basse", "bas"],
    "mbw": ["arc musical"],
    "mbx": ["boîte à musique", "tabatière"],
    "mcb": ["cristal Baschet"],
    "mck": ["eschiquier", "archiquier"],
    "mck": ["eschiquier", "échiquier"],
    "mck": ["eschiquier", "eschaqueil d'angleterre"],
    "mck": ["eschiquier", "exaquier"],
    "mcl": ["horloge musicale"],
    "mco": ["basse continue", "basse chiffrée"],
    "mco": ["basse continue", "basse fondamentale"],
    "mgh": ["harmonica de verre", "euphone"],
    "mgh": ["harmonica de verre", "verrillon"],
    "mgt": ["trompette de verre"],
    "mha": ["harmonica", "harmonica à bouche"],
    "mhg": ["vielle à roue", "chifonie"],
    "mhg": ["vielle à roue", "chinforgne"],
    "mhg": ["vielle à roue", "ciphonie"],
    "mhg": ["vielle à roue", "clavecin-vielle"],
    "mhg": ["vielle à roue", "symphonie"],
    "mhg": ["vielle à roue", "vielle organisée"],
    "mjh": ["guimbarde", "trompe de béarn"],
    "mla": ["lamellophone"],
    "mmc": ["monocorde"],
    "mme": ["mélodica"],
    "mmi": ["mirliton", "flûte à l'oignon"],
    "mmi": ["mirliton", "flûte eunuque"],
    "mml": ["instrument mélodique"],
    "mms": ["scie musicale", "lame sonore"],
    "mpo": ["instrument harmonique", "instrument polyphonique"],
    "mpp": ["piano mécanique"],
    "msw": ["flûte à coulisse", "jazz flûte"],
    "mui": ["instrument"],
    "mui__y": ["instrument - ethnique"],
    "mun": ["instrument ou voix"],
    "mwd": ["instrument à vent"],
    "mwh": ["sifflet"],
    "mzz": ["autre", "divers"],
    "oba": ["harmonie"],
    "obr": ["fanfare"],
    "och": ["orchestre de chambre"],
    "odo": ["orchestre de danse"],
    "ofu": ["orchestre symphonique", "grand orchestre"],
    "oga": ["gamelan"],
    "oie": ["ensemble instrumental"],
    "oiv": ["ensemble vocal et instrumental"],
    "oja": ["ensemble de jazz"],
    "ope": ["orchestre de percussions", "instrumentarium orff"],
    "ost": ["orchestre à cordes"],
    "oun": ["orchestre"],
    "oun__y": ["orchestre - ethnique"],
    "owi": ["orchestre de vents"],
    "ozz": ["orchestre - autre"],
    "pab": ["clochettes suspendues", "baguettes de verre"],
    "pab": ["clochettes suspendues", "cloches de coquille"],
    "pab": ["clochettes suspendues", "cloches de verre"],
    "pab": ["clochettes suspendues", "clochette à vent"],
    "pab": ["clochettes suspendues", "clochette chinoise à vent"],
    "pab": ["clochettes suspendues", "clochettes éoliennes"],
    "pab": ["clochettes suspendues", "plaquettes de verre"],
    "pad": ["darbouka", "derbouka"],
    "pad": ["darbouka", "tambour arabe"],
    "pag": ["agogô", "gongué"],
    "pan": ["enclume"],
    "pbd": ["grosse caisse", "grand tambour"],
    "pbd": ["grosse caisse", "tonnant"],
    "pbe": ["tambourin de béarn", "tambourin à cordes"],
    "pbe": ["tambourin de béarn", "tambourin de gascogne"],
    "pbe": ["tambourin de béarn", "trombe"],
    "pbl": ["cloches", "cloche"],
    "pbl": ["cloches", "cloches tubes"],
    "pbo": ["bongo"],
    "pbp": ["cloches-plaques", "cloches à plaque"],
    "pbp": ["cloches-plaques", "cloches en lame de métal"],
    "pbr": ["bronté"],
    "pca": ["castagnettes", "cliquettes"],
    "pcb": ["calebasse"],
    "pcc": ["cymbales chinoises"],
    "pcg": ["conga", "tambour congo"],
    "pch": ["chaînes"],
    "pci": ["cymbalum", "doucemelle"],
    "pci": ["cymbalum", "doulcemelle"],
    "pci": ["cymbalum", "dulçema"],
    "pci": ["cymbalum", "dulcet"],
    "pci": ["cymbalum", "dulcette"],
    "pci": ["cymbalum", "psaltérion"],
    "pci": ["cymbalum", "tympanon"],
    "pcr": ["cymbale suspendue"],
    "pct": ["crotales", "cymbales antiques"],
    "pcv": ["claves", "baguettes"],
    "pcw": ["cloche de vache", "cloche à vache"],
    "pcw": ["cloche de vache", "grelot de vache"],
    "pcy": ["cymbale", "cymbales à main"],
    "pcy": ["cymbale", "cymbales coquées"],
    "pcy": ["cymbale", "cymbales frappées"],
    "pcy": ["cymbale", "cymbales"],
    "pdr": ["tambour"],
    "pds": ["batterie", "équipement de la batterie"],
    "pfc": ["cymbales digitales", "castagnettes de fer"],
    "pfc": ["cymbales digitales", "cliquettes métalliques"],
    "pfc": ["cymbales digitales", "crotales à doigts"],
    "pfc": ["cymbales digitales", "cymbales à doigts"],
    "pfd": ["tambour à friction", "tambour à corde"],
    "pfl": ["flexatone"],
    "pgn": ["canon"],
    "pgo": ["tam-tam"],
    "pha": ["marteau", "massue"],
    "phb": ["cloches à main", "clochette à main"],
    "phb": ["cloches à main", "clochette de messe"],
    "phb": ["cloches à main", "clochette pour la messe"],
    "phb": ["cloches à main", "clochette"],
    "phh": ["cymbales charleston", "charleston"],
    "phh": ["cymbales charleston", "cymbales à pedale"],
    "pji": ["grelots", "araine"],
    "pji": ["grelots", "grelot"],
    "pji": ["grelots", "sonnaille"],
    "pji": ["grelots", "sonneau"],
    "pji": ["grelots", "sonnette"],
    "pli": ["lithophone"],
    "pmb": ["marimba", "marimbaphone"],
    "pmd": ["tambour militaire", "caisse claire"],
    "pmd": ["tambour militaire", "caisse plate"],
    "pmd": ["tambour militaire", "caisse roulante"],
    "pmd": ["tambour militaire", "caisse sourde"],
    "pmd": ["tambour militaire", "caisse"],
    "pmd": ["tambour militaire", "tambour à timbre"],
    "pmd": ["tambour militaire", "tambour d'empire"],
    "pmd": ["tambour militaire", "tambour de Bâle"],
    "pmd": ["tambour militaire", "tambour de parade"],
    "pmd": ["tambour militaire", "tambour roulant"],
    "pmd": ["tambour militaire", "tambour ténor"],
    "pmd": ["tambour militaire", "tambourin de Suisse"],
    "pme": ["métallophone"],
    "pnv": ["violon de fer"],
    "pra": ["crécelle", "tartevelle"],
    "prs": ["bâton de pluie"],
    "psc": ["cymbale cloutée"],
    "pse": ["objet sonore"],
    "psl": ["tambour de bois à fente", "tambour à fente"],
    "psl": ["tambour de bois à fente", "tambour à fessure"],
    "psl": ["tambour de bois à fente", "tambour de bois"],
    "psl": ["tambour de bois à fente", "tambour de tronc d'arbre"],
    "psm": ["sistre"],
    "psn": ["sirène"],
    "psp": ["papier de verre", "blocs à papier de verre"],
    "psp": ["papier de verre", "sandpapier"],
    "pss": ["sculpture sonore", "structure Bascet"],
    "pst": ["tambour d'acier"],
    "psw": ["fouet de verges", "verges"],
    "ptb": ["tambourin", "tabolet"],
    "ptb": ["tambourin", "taboret"],
    "ptb": ["tambourin", "tambour provençal"],
    "ptb": ["tambourin", "tambour sur cadre"],
    "ptb": ["tambourin", "tambourin de provence"],
    "ptb": ["tambourin", "tambourine"],
    "ptc": ["chapeau chinois", "bonnet chinois"],
    "ptc": ["chapeau chinois", "pavillon chinois"],
    "ptg": ["gong", "gong accordé"],
    "pti": ["timbales", "nacaires"],
    "pti": ["timbales", "timbale chromatique"],
    "pti": ["timbales", "timbale-trompette"],
    "pti": ["timbales", "timbale"],
    "pti": ["timbales", "trompette-timbale"],
    "ptl": ["triangle"],
    "ptm": ["machine à tonnerre", "tôle pour imiter le tonnerre"],
    "pto": ["tarole"],
    "ptr": ["tambour de basque", "bedon de biscaye"],
    "ptr": ["tambour de basque", "doira"],
    "ptr": ["tambour de basque", "piano-basque"],
    "ptr": ["tambour de basque", "timbrel"],
    "ptt": ["tom"],
    "pun": ["percussions"],
    "pun__s": ["percussion électronique"],
    "pun__y": ["percussions - ethnique"],
    "pvi": ["vibraphone"],
    "pwh": ["fouet", "claquette"],
    "pwm": ["machine à vent", "aeoliphone"],
    "pwo": ["woodblock", "bloc chinois"],
    "pwo": ["woodblock", "bloc de bois cylindrique"],
    "pwo": ["woodblock", "blocs chinois en bois"],
    "pwo": ["woodblock", "blocs de bois"],
    "pxr": ["xylorimba"],
    "pxy": ["xylophone", "balafon"],
    "pxy": ["xylophone", "claquebois"],
    "pxy": ["xylophone", "échelette"],
    "pxy": ["xylophone", "eschelletes"],
    "pxy": ["xylophone", "orgue de bois"],
    "pxy": ["xylophone", "patouilles"],
    "pxy": ["xylophone", "régale de bois"],
    "pzz": ["percussions - autre"],
    "qch": ["chef de choeur", "chef de chœur"],
    "qco": ["chef d'orchestre"],
    "qzz": ["directeur - autre"],
    "sar": ["arpeggione", "guitare d'amour"],
    "sar": ["arpeggione", "guitare-violoncelle"],
    "sba": ["baryton"],
    "sbt": ["basset"],
    "sbu": ["basse de flandre", "basse à boyau"],
    "sbu": ["basse de flandre", "guimbarde à corde"],
    "sdb": ["contrebasse", "basse des italiens"],
    "sdb": ["contrebasse", "basse-contre"],
    "sdb": ["contrebasse", "contraviolon"],
    "sdf": ["contrebasse à cinq cordes"],
    "sfi": ["vièle (famille)", "vièle"],
    "sob": ["octobasse", "basse gigantesque"],
    "spo": ["pochette", "poche"],
    "spo": ["pochette", "sourdine"],
    "spv": ["pardessus de viole"],
    "spv": ["quinton"],
    "sre": ["rebec", "gigue"],
    "sre": ["rebec", "rabec"],
    "sre": ["rebec", "rabecq"],
    "sre": ["rebec", "rebebe"],
    "sre": ["rebec", "rebecq"],
    "sre": ["rebec", "rebecquet"],
    "sre": ["rebec", "rebelle"],
    "sre": ["rebec", "rebequin"],
    "sre": ["rebec", "reberbe"],
    "sre": ["rebec", "rebesbe"],
    "sre": ["rebec", "robecq"],
    "sre": ["rebec", "rubebe"],
    "stm": ["trompette marine"],
    "sun": ["cordes frottées"],
    "sun__y": ["cordes frottées - ethnique"],
    "sva": ["alto", "haute-contre de violon"],
    "sva": ["alto", "quinte de violon"],
    "sva": ["alto", "taille de violon"],
    "svc": ["violoncelle", "bas de violon"],
    "svc": ["violoncelle", "bas viol de braccio"],
    "svc": ["violoncelle", "basse de violon"],
    "svd": ["viole d'amour"],
    "svg": ["viole de gambe"],
    "svgf": ["basse de viole"],
    "svl": ["violon", "dessus de violon"],
    "szz": ["cordes frottées - autre"],
    "tal": ["archiluth", "angélique"],
    "tat": ["arpanette", "arpe pointue"],
    "tbj": ["banjo"],
    "tci": ["cistre", "archicistre"],
    "tci": ["cistre", "cistra"],
    "tci": ["cistre", "cithre"],
    "tci": ["cistre", "guitare allemande"],
    "tci": ["cistre", "guitare anglaise"],
    "tct": ["citole"],
    "tgu": ["guitare", "guitare capucine"],
    "tgu": ["guitare", "guitare en bateau"],
    "tgu": ["guitare", "guitarre"],
    "tgu__r": ["guitare électrique"],
    "tguf_r": ["gitare électrique basse"],
    "tha": ["harpe"],
    "thg": ["guitare hawaïenne"],
    "tih": ["harpe celtique"],
    "tko": ["kora"],
    "tkt": ["koto"],
    "tlf": ["lute (famille)"],
    "tlg": ["lyre-guitare", "lyre anacréontique"],
    "tlg": ["lyre-guitare", "lyre organisée"],
    "tlg": ["lyre-guitare", "lyre"],
    "tlu": ["luth"],
    "tma": ["mandoline"],
    "tmd": ["mandore", "gallichon"],
    "tmd": ["mandore", "mandoire"],
    "tmd": ["mandore", "mandole"],
    "tmd": ["mandore", "mandolle"],
    "tps": ["psaltérion", "saltere"],
    "tps": ["psaltérion", "sauterie"],
    "tps": ["psaltérion", "sautier"],
    "tps": ["psaltérion", "sautiéron"],
    "tth": ["théorbe", "tuorbe"],
    "ttn": ["tambûr"],
    "tuk": ["ukulélé"],
    "tun": ["cordes pincées"],
    "tun__y": ["cordes pincées - ethnique"],
    "tzi": ["cithare", "autoharpe"],
    "tzi": ["cithare", "bûche de flandres"],
    "tzi": ["cithare", "bûche"],
    "tzi": ["cithare", "épinette des vosges"],
    "tzz": ["cordes pincées - autre"],
    "val": ["contralto"],
    "vbr": ["baryton", "baryton Martin"],
    "vbr": ["baryton", "baryton Verdi"],
    "vbs": ["basse", "bas"],
    "vca": ["alto enfant"],
    "vcs": ["soprano enfant"],
    "vct": ["contre-ténor", "haute-contre"],
    "vcv": ["voix d'enfant", "voix enfantine"],
    "vhc": ["haute-contre"],
    "vma": ["voix d'homme"],
    "vrc": ["récitant enfant", "voix parlée enfant"],
    "vre": ["voix parlée", "récitant"],
    "vrm": ["récitant homme", "voix parlée homme"],
    "vrw": ["récitante", "voix parlée femme"],
    "vso": ["soprano", "dessus"],
    "vte": ["ténor", "taille (voix)"],
    "vte": ["ténor", "ténorino"],
    "vun": ["voix", "chant"],
    "vun": ["voix", "partie vocale"],
    "vun__w": ["voix enregistrée"],
    "vun__y": ["voix - ethnique"],
    "vunj": ["voix haute"],
    "vunk": ["voix moyenne"],
    "vunl": ["voix grave"],
    "vwo": ["voix de femme"],
    "vzz": ["voix - autre"],
    "wba": ["basson", "fagot"],
    "wbh": ["cor de basset"],
    "wbp": ["cornemuse", "biniou"],
    "wbp": ["cornemuse", "cabrette"],
    "wbp": ["cornemuse", "sourdeline"],
    "wbp": ["cornemuse", "vèze"],
    "wch": ["chalumeau", "calimiau"],
    "wch": ["chalumeau", "chalemiau"],
    "wch": ["chalumeau", "chalimou"],
    "wcl": ["clarinette"],
    "wclf": ["clarinette basse", "basse-guerrière"],
    "wclf": ["clarinette basse", "basse-orgue"],
    "wclg": ["bathyphone", "batyphone"],
    "wclj": ["clarinetto piccolo"],
    "wcr": ["cromorne", "tournebout"],
    "wdb": ["contrebasson"],
    "wdu": ["dolçaine"],
    "weh": ["cor anglais", "taille de hautbois d'amour"],
    "wfa": ["flûte d'amour"],
    "wfg": ["flageolet"],
    "wfi": ["fifre"],
    "wfl": ["flûte", "flûte allemande"],
    "wfl": ["flûte", "flûte d'allemagne"],
    "wfl": ["flûte", "flûte traversière"],
    "wfl": ["flûte", "traversière"],
    "wflf": ["flûte basse"],
    "wga": ["galoubet", "flûte à trois trous"],
    "wga": ["galoubet", "flutet"],
    "wge": ["cor de chamois"],
    "wmo": ["orgue à bouche"],
    "wmu": ["musette"],
    "woa": ["hautbois d'amour"],
    "wob": ["hautbois", "haut-bois"],
    "wobe": ["heckelphone"],
    "wpi": ["piccolo", "petite flûte"],
    "wpo": ["bombarde", "chalemelle"],
    "wpo": ["bombarde", "chalemie"],
    "wpo": ["bombarde", "chalmeye"],
    "wpp": ["flûte de pan", "flûte pastorelle"],
    "wra": ["cervelas", "racquette"],
    "wre": ["flûte à bec", "flauste"],
    "wre": ["flûte à bec", "flaute"],
    "wre": ["flûte à bec", "flûte à neuf trous"],
    "wre": ["flûte à bec", "flûte d'angleterre"],
    "wro": ["rothophone"],
    "wsa": ["saxophone", "ophicléide á clefs et á bec"],
    "wsa": ["saxophone", "ophicléide á clefs"],
    "wsn": ["surna"],
    "wsr": ["sarrusophone", "contrebasse à anche"],
    "wsu": ["courtaut", "sourdine"],
    "wun": ["bois"],
    "wun__y": ["bois - ethnique"],
    "wzz": ["bois - autre"],
    "zab": ["acrobate"],
    "zac": ["acteur enfant"],
    "zas": ["acteur muet"],
    "zat": ["acteur", "comédien"],
    "zaw": ["actrice", "comédienne"],
    "zda": ["danseur", "danseuse"],
    "zes": ["ingénieur du son"],
    "zju": ["jongleur"],
    "zmi": ["mime"],
    "zwp": ["figurant"],
    "zzz": ["interprète - autre"],
}
