iaml = {
    "bah": ["cor des Alpes"],
    "bbb": ["saxhorn baryton", "saxtromba baryton"],
    "bbd": ["bombardone", "basse impériale", "bombardone", "saxhorn basse"],
    "bbu": ["clairon", "bugle baryton", "clairon", "bugleret", "clairon", "cor buglèr"],
    "bbu": ["clairon", "cor bugleret"],
    "bco": ["cornet à pistons", "piston"],
    "bct": ["cornet à bouquin", "cornaboux"],
    "bdx": ["dublophone", "lyrophone"],
    "beu": [
        "euphonium",
        "baritone",
        "euphonium",
        "baryton en sib",
        "euphonium",
        "basse à pistons",
        "euphonium",
        "basse en sib",
        "euphonium",
        "basse impériale",
    ],
    "bhh": ["cor de chasse", "huchet", "cor de chasse", "trompe de chasse"],
    "bho": [
        "cor",
        "cor à piston",
        "cor",
        "cor d'harmonie",
        "cor",
        "cor naturel",
        "cor",
        "cor simple",
        "cor",
        "trompe",
    ],
    "bht": [
        "buisine",
        "bousine",
        "buisine",
        "busine",
        "buisine",
        "buysine",
        "buisine",
        "buzine",
    ],
    "bkb": [
        "bugle à clefs",
        "cor à clefs",
        "bugle à clefs",
        "taille d'amour",
        "bugle à clefs",
        "trompette à clefs",
    ],
    "bol": ["cor d'olifant", "oliphant"],
    "bop": [
        "ophicleïde",
        "basse à clefs",
        "ophicleïde",
        "basse d'harmonie",
        "ophicleïde",
        "contrebasse d'harmonie",
        "ophicleïde",
        "serpentcleide",
        "ophicleïde",
        "tuba-dupré",
    ],
    "bph": ["cornet de poste", "cornet de postillon"],
    "brh": ["cor russe"],
    "bse": [
        "serpent",
        "basse-cor",
        "serpent",
        "basse-trompette",
        "serpent",
        "basson russe",
        "serpent",
        "basson serpent",
        "serpent",
        "serpent d'église",
        "serpent",
        "serpent droit",
        "serpent",
        "serpent militaire",
        "serpent",
        "serpenton",
    ],
    "bsh": ["chofar", "chophar"],
    "btb": [
        "trombone à coulisse",
        "sacqueboute",
        "trombone à coulisse",
        "saicqueboute",
        "trombone à coulisse",
        "saqueboute",
        "trombone à coulisse",
        "trompette saqueboute",
        "trombone",
        "sacqueboute",
        "trombone",
        "saicqueboute",
        "trombone",
        "saqueboute",
        "trombone",
        "trompette saqueboute",
    ],
    "btr": ["trompette"],
    "btu": ["tuba"],
    "bun": ["cuivre"],
    "bun__y": ["cuivre - ethnique"],
    "bvb": ["bugle à pistons", "saxhorn", "bugle à pistons", "sudrophone"],
    "bvba": ["petit bugle", "bugle soprano en Mib", "petit bugle", "saxhorn sopranino"],
    "bvbb": ["bugle", "saxhorn soprano"],
    "bvbc": [
        "saxhorn alto",
        "alto en Mib",
        "saxhorn alto",
        "baryton aigu",
        "saxhorn alto",
        "bugle alto",
        "saxhorn alto",
        "clavicor",
        "saxhorn alto",
        "tenor cor",
        "saxhorn alto",
        "ténor en Mib",
    ],
    "bvbd": [
        "saxhorn ténor",
        "baryton",
        "saxhorn ténor",
        "bugle ténor",
        "saxhorn ténor",
        "clavicor",
    ],
    "bvbi": ["petit saxhorn suraigu"],
    "bzz": ["cuivre - autre"],
    "cch": ["choeur d'enfants", "chœur d'enfants"],
    "cme": ["choeur d'hommes", "chœur d'hommes"],
    "cmi": ["choeur mixte", "chœur mixte"],
    "cre": ["choeur parlé", "chœur parlé"],
    "cun": ["choeur", "chœur"],
    "cun__y": ["choeur - ethnique"],
    "cve": ["ensemble vocal"],
    "cwo": ["choeur de femmes", "chœur de femmes"],
    "czz": ["choeur - autre"],
    "eco": [
        "ordinateur",
        "ordinateur portable",
        "ordinateur",
        "processeur numérique",
        "station informatique musicale",
    ],
    "ect": ["bande réalisée par ordinateur, sons fixés"],
    "eea": ["dispositif électroacoustique"],
    "eli": ["dispositif électronique temps réel"],
    "ema": ["ondes Martenot"],
    "eme": ["méta-instrument"],
    "emu": ["dispositif multimédia"],
    "eos": ["oscillateur"],
    "esp": ["dispositif spatial"],
    "esy": ["synthétiseur"],
    "eta": ["bande magnétique"],
    "eth": ["thereminovox"],
    "eun": ["instrument électronique"],
    "ezz": ["instrument électronique - autre"],
    "kac": ["accordéon", "harmonieflûte"],
    "kba": ["bandonéon"],
    "kca": ["carillon", "jeu de timbres"],
    "kca": ["carillon", "timbres"],
    "kce": ["célesta", "adiaphone", "célesta", "céleste"],
    "kch": ["chordette"],
    "kcl": [
        "clavicorde",
        "épinette sourde",
        "clavicorde",
        "manicorde",
        "clavicorde",
        "manicordion",
    ],
    "kco": ["clavecin organisé", "épinette organisée"],
    "kfp": ["pianoforte", "piano-forte"],
    "kgl": ["glockenspiel"],
    "khm": [
        "harmonium",
        "harmonicorde",
        "harmonium",
        "orgue américain",
        "harmonium",
        "orgue expressif",
        "harmonium",
        "piano-chanteur",
        "harmonium",
        "poïkilorgue",
        "harmonium",
        "séraphine",
    ],
    "khp": ["clavecin", "clavecin brisé", "clavecin", "clavessin"],
    "kor": ["orgue", "orgue positif", "orgue", "orgues"],
    "kor__r": ["orgue électrique", "orgue hammond"],
    "kpf": [
        "luthéal",
        "piano cycloide",
        "piano droit",
        "piano elliptique",
        "piano-luthéal",
        "piano luthéal",
        "piano lutheal",
    ],
    "kpf__r": ["piano électrique"],
    "kpf__s": ["piano électronique"],
    "kps": ["clavier à cordes pincées"],
    "kun": ["clavier", "instrument à clavier"],
    "kun__y": ["clavier - ethnique"],
    "kzz": ["clavier - autre"],
    "mah": [
        "harpe éolienne",
        "aéro-clavicorde",
        "harpe éolienne",
        "anémocorde",
        "harpe éolienne",
        "piano éolien",
    ],
    "mbo": ["orgue à manivelle", "orgue de barbarie"],
    "mbr": ["rhombe", "planchette ronflante"],
    "mbs": ["basse", "bas"],
    "mbw": ["arc musical"],
    "mbx": ["boîte à musique", "tabatière"],
    "mcb": ["cristal Baschet"],
    "mck": [
        "eschiquier",
        "archiquier",
        "eschiquier",
        "échiquier",
        "eschiquier",
        "eschaqueil d'angleterre",
        "eschiquier",
        "exaquier",
    ],
    "mcl": ["horloge musicale"],
    "mco": ["basse continue", "basse chiffrée", "basse continue", "basse fondamentale"],
    "mgh": ["harmonica de verre", "euphone", "harmonica de verre", "verrillon"],
    "mgt": ["trompette de verre"],
    "mha": ["harmonica", "harmonica à bouche"],
    "mhg": [
        "vielle à roue",
        "chifonie",
        "vielle à roue",
        "chinforgne",
        "vielle à roue",
        "ciphonie",
        "vielle à roue",
        "clavecin-vielle",
        "vielle à roue",
        "symphonie",
        "vielle à roue",
        "vielle organisée",
    ],
    "mjh": ["guimbarde", "trompe de béarn"],
    "mla": ["lamellophone"],
    "mmc": ["monocorde"],
    "mme": ["mélodica"],
    "mmi": ["mirliton", "flûte à l'oignon", "mirliton", "flûte eunuque"],
    "mml": ["instrument mélodique"],
    "mms": ["scie musicale", "lame sonore"],
    "mpo": ["instrument harmonique", "instrument polyphonique"],
    "mpp": ["piano mécanique"],
    "msw": ["flûte à coulisse", "jazz flûte"],
    "mui": ["instrument"],
    "mui__y": ["instrument - ethnique"],
    "mun": ["instrument ou voix"],
    "mwd": ["instrument à vent"],
    "mwh": ["sifflet"],
    "mzz": ["autre", "divers"],
    "oba": ["harmonie"],
    "obr": ["fanfare"],
    "och": ["orchestre de chambre"],
    "odo": ["orchestre de danse"],
    "ofu": ["orchestre symphonique", "grand orchestre"],
    "oga": ["gamelan"],
    "oie": ["ensemble instrumental"],
    "oiv": ["ensemble vocal et instrumental"],
    "oja": ["ensemble de jazz"],
    "ope": ["orchestre de percussions", "instrumentarium orff"],
    "ost": ["orchestre à cordes"],
    "oun": ["orchestre"],
    "oun__y": ["orchestre - ethnique"],
    "owi": ["orchestre de vents"],
    "ozz": ["orchestre - autre"],
    "pab": [
        "clochettes suspendues",
        "baguettes de verre",
        "clochettes suspendues",
        "cloches de coquille",
        "clochettes suspendues",
        "cloches de verre",
        "clochettes suspendues",
        "clochette à vent",
        "clochettes suspendues",
        "clochette chinoise à vent",
        "clochettes suspendues",
        "clochettes éoliennes",
        "clochettes suspendues",
        "plaquettes de verre",
    ],
    "pad": ["darbouka", "derbouka", "darbouka", "tambour arabe"],
    "pag": ["agogô", "gongué"],
    "pan": ["enclume"],
    "pbd": ["grosse caisse", "grand tambour", "grosse caisse", "tonnant"],
    "pbe": [
        "tambourin de béarn",
        "tambourin à cordes",
        "tambourin de béarn",
        "tambourin de gascogne",
        "tambourin de béarn",
        "trombe",
    ],
    "pbl": ["cloches", "cloche"],
    "pbl": ["cloches", "cloches tubes"],
    "pbo": ["bongo"],
    "pbp": [
        "cloches-plaques",
        "cloches à plaque",
        "cloches-plaques",
        "cloches en lame de métal",
    ],
    "pbr": ["bronté"],
    "pca": ["castagnettes", "cliquettes"],
    "pcb": ["calebasse"],
    "pcc": ["cymbales chinoises"],
    "pcg": ["conga", "tambour congo"],
    "pch": ["chaînes"],
    "pci": [
        "cymbalum",
        "doucemelle",
        "cymbalum",
        "doulcemelle",
        "cymbalum",
        "dulçema",
        "cymbalum",
        "dulcet",
        "cymbalum",
        "dulcette",
        "cymbalum",
        "psaltérion",
        "cymbalum",
        "tympanon",
    ],
    "pcr": ["cymbale suspendue"],
    "pct": ["crotales", "cymbales antiques"],
    "pcv": ["claves", "baguettes"],
    "pcw": ["cloche de vache", "cloche à vache"],
    "pcw": ["cloche de vache", "grelot de vache"],
    "pcy": [
        "cymbale",
        "cymbales à main",
        "cymbale",
        "cymbales coquées",
        "cymbale",
        "cymbales frappées",
        "cymbale",
        "cymbales",
    ],
    "pdr": ["tambour"],
    "pds": ["batterie", "équipement de la batterie"],
    "pfc": [
        "cymbales digitales",
        "castagnettes de fer",
        "cymbales digitales",
        "cliquettes métalliques",
        "cymbales digitales",
        "crotales à doigts",
        "cymbales digitales",
        "cymbales à doigts",
    ],
    "pfd": ["tambour à friction", "tambour à corde"],
    "pfl": ["flexatone"],
    "pgn": ["canon"],
    "pgo": ["tam-tam"],
    "pha": ["marteau", "massue"],
    "phb": [
        "cloches à main",
        "clochette à main",
        "cloches à main",
        "clochette de messe",
        "cloches à main",
        "clochette pour la messe",
        "cloches à main",
        "clochette",
    ],
    "phh": [
        "cymbales charleston",
        "charleston",
        "cymbales charleston",
        "cymbales à pedale",
    ],
    "pji": [
        "grelots",
        "araine",
        "grelots",
        "grelot",
        "grelots",
        "sonnaille",
        "grelots",
        "sonneau",
        "grelots",
        "sonnette",
    ],
    "pli": ["lithophone"],
    "pmb": ["marimba", "marimbaphone"],
    "pmd": [
        "tambour militaire",
        "caisse claire",
        "tambour militaire",
        "caisse plate",
        "tambour militaire",
        "caisse roulante",
        "tambour militaire",
        "caisse sourde",
        "tambour militaire",
        "caisse",
        "tambour militaire",
        "tambour à timbre",
        "tambour militaire",
        "tambour d'empire",
        "tambour militaire",
        "tambour de Bâle",
        "tambour militaire",
        "tambour de parade",
        "tambour militaire",
        "tambour roulant",
        "tambour militaire",
        "tambour ténor",
        "tambour militaire",
        "tambourin de Suisse",
    ],
    "pme": ["métallophone"],
    "pnv": ["violon de fer"],
    "pra": ["crécelle", "tartevelle"],
    "prs": ["bâton de pluie"],
    "psc": ["cymbale cloutée"],
    "pse": ["objet sonore"],
    "psl": [
        "tambour de bois à fente",
        "tambour à fente",
        "tambour de bois à fente",
        "tambour à fessure",
        "tambour de bois à fente",
        "tambour de bois",
        "tambour de bois à fente",
        "tambour de tronc d'arbre",
    ],
    "psm": ["sistre"],
    "psn": ["sirène"],
    "psp": [
        "papier de verre",
        "blocs à papier de verre",
        "papier de verre",
        "sandpapier",
    ],
    "pss": ["sculpture sonore", "structure Bascet"],
    "pst": ["tambour d'acier"],
    "psw": ["fouet de verges", "verges"],
    "ptb": [
        "tambourin",
        "tabolet",
        "tambourin",
        "taboret",
        "tambourin",
        "tambour provençal",
        "tambourin",
        "tambour sur cadre",
        "tambourin",
        "tambourin de provence",
        "tambourin",
        "tambourine",
    ],
    "ptc": ["chapeau chinois", "bonnet chinois", "chapeau chinois", "pavillon chinois"],
    "ptg": ["gong", "gong accordé"],
    "pti": [
        "timbales",
        "nacaires",
        "timbales",
        "timbale chromatique",
        "timbales",
        "timbale-trompette",
        "timbales",
        "timbale",
        "timbales",
        "trompette-timbale",
    ],
    "ptl": ["triangle"],
    "ptm": ["machine à tonnerre", "tôle pour imiter le tonnerre"],
    "pto": ["tarole"],
    "ptr": [
        "tambour de basque",
        "bedon de biscaye",
        "tambour de basque",
        "doira",
        "tambour de basque",
        "piano-basque",
        "tambour de basque",
        "timbrel",
    ],
    "ptt": ["tom"],
    "pun": ["percussions"],
    "pun__s": ["percussion électronique"],
    "pun__y": ["percussions - ethnique"],
    "pvi": ["vibraphone"],
    "pwh": ["fouet", "claquette"],
    "pwm": ["machine à vent", "aeoliphone"],
    "pwo": [
        "woodblock",
        "bloc chinois",
        "woodblock",
        "bloc de bois cylindrique",
        "woodblock",
        "blocs chinois en bois",
        "woodblock",
        "blocs de bois",
    ],
    "pxr": ["xylorimba"],
    "pxy": [
        "xylophone",
        "balafon",
        "xylophone",
        "claquebois",
        "xylophone",
        "échelette",
        "xylophone",
        "eschelletes",
        "xylophone",
        "orgue de bois",
        "xylophone",
        "patouilles",
        "xylophone",
        "régale de bois",
    ],
    "pzz": ["percussions - autre"],
    "qch": ["chef de choeur", "chef de chœur"],
    "qco": ["chef d'orchestre"],
    "qzz": ["directeur - autre"],
    "sar": ["arpeggione", "guitare d'amour", "arpeggione", "guitare-violoncelle"],
    "sba": ["baryton"],
    "sbt": ["basset"],
    "sbu": [
        "basse de flandre",
        "basse à boyau",
        "basse de flandre",
        "guimbarde à corde",
    ],
    "sdb": [
        "contrebasse",
        "basse des italiens",
        "contrebasse",
        "basse-contre",
        "contrebasse",
        "contraviolon",
    ],
    "sdf": ["contrebasse à cinq cordes"],
    "sfi": ["vièle (famille)", "vièle"],
    "sob": ["octobasse", "basse gigantesque"],
    "spo": ["pochette", "poche", "pochette", "sourdine"],
    "spv": ["pardessus de viole", "quinton"],
    "sre": [
        "rebec",
        "gigue",
        "rebec",
        "rabec",
        "rebec",
        "rabecq",
        "rebec",
        "rebebe",
        "rebec",
        "rebecq",
        "rebec",
        "rebecquet",
        "rebec",
        "rebelle",
        "rebec",
        "rebequin",
        "rebec",
        "reberbe",
        "rebec",
        "rebesbe",
        "rebec",
        "robecq",
        "rebec",
        "rubebe",
    ],
    "stm": ["trompette marine"],
    "sun": ["cordes frottées"],
    "sun__y": ["cordes frottées - ethnique"],
    "sva": [
        "alto",
        "haute-contre de violon",
        "altos",
        "quinte de violon",
        "taille de violon",
    ],
    "svc": [
        "violoncelle",
        "bas de violon",
        "violoncelle",
        "bas viol de braccio",
        "violoncelle",
        "basse de violon",
    ],
    "svd": ["viole d'amour"],
    "svg": ["viole de gambe"],
    "svgf": ["basse de viole"],
    "svl": ["violon", "dessus de violon"],
    "szz": ["cordes frottées - autre"],
    "tal": ["archiluth", "angélique"],
    "tat": ["arpanette", "arpe pointue"],
    "tbj": ["banjo"],
    "tci": [
        "cistre",
        "archicistre",
        "cistre",
        "cistra",
        "cistre",
        "cithre",
        "cistre",
        "guitare allemande",
        "cistre",
        "guitare anglaise",
    ],
    "tct": ["citole"],
    "tgu": [
        "guitare",
        "guitare capucine",
        "guitare",
        "guitare en bateau",
        "guitare",
        "guitarre",
    ],
    "tgu__r": ["guitare électrique"],
    "tguf_r": ["gitare électrique basse"],
    "tha": ["harpe"],
    "thg": ["guitare hawaïenne"],
    "tih": ["harpe celtique"],
    "tko": ["kora"],
    "tkt": ["koto"],
    "tlf": ["lute (famille)"],
    "tlg": [
        "lyre-guitare",
        "lyre anacréontique",
        "lyre-guitare",
        "lyre organisée",
        "lyre-guitare",
        "lyre",
    ],
    "tlu": ["luth"],
    "tma": ["mandoline"],
    "tmd": [
        "mandore",
        "gallichon",
        "mandore",
        "mandoire",
        "mandore",
        "mandole",
        "mandore",
        "mandolle",
    ],
    "tps": [
        "psaltérion",
        "saltere",
        "psaltérion",
        "sauterie",
        "psaltérion",
        "sautier",
        "psaltérion",
        "sautiéron",
    ],
    "tth": ["théorbe", "tuorbe"],
    "ttn": ["tambûr"],
    "tuk": ["ukulélé"],
    "tun": ["cordes pincées"],
    "tun__y": ["cordes pincées - ethnique"],
    "tzi": [
        "cithare",
        "autoharpe",
        "cithare",
        "bûche de flandres",
        "cithare",
        "bûche",
        "cithare",
        "épinette des vosges",
    ],
    "tzz": ["cordes pincées - autre"],
    "val": ["contralto"],
    "vbr": ["baryton", "baryton Martin", "baryton", "baryton Verdi"],
    "vbs": ["basse", "bas"],
    "vca": ["alto enfant"],
    "vcs": ["soprano enfant"],
    "vct": ["contre-ténor", "haute-contre"],
    "vcv": ["voix d'enfant", "voix enfantine"],
    "vhc": ["haute-contre"],
    "vma": ["voix d'homme"],
    "vrc": ["récitant enfant", "voix parlée enfant"],
    "vre": ["voix parlée", "récitant"],
    "vrm": ["récitant homme", "voix parlée homme"],
    "vrw": ["récitante", "voix parlée femme"],
    "vso": ["soprano", "dessus"],
    "vte": ["ténor", "taille (voix)", "ténor", "ténorino"],
    "vun": ["voix", "chant", "voix", "partie vocale"],
    "vun__w": ["voix enregistrée"],
    "vun__y": ["voix - ethnique"],
    "vunj": ["voix haute"],
    "vunk": ["voix moyenne"],
    "vunl": ["voix grave"],
    "vwo": ["voix de femme"],
    "vzz": ["voix - autre"],
    "wba": ["basson", "fagot"],
    "wbh": ["cor de basset"],
    "wbp": [
        "cornemuse",
        "biniou",
        "cornemuse",
        "cabrette",
        "cornemuse",
        "sourdeline",
        "cornemuse",
        "vèze",
    ],
    "wch": ["chalumeau", "calimiau", "chalumeau", "chalemiau", "chalumeau", "chalimou"],
    "wcl": ["clarinette"],
    "wclf": ["clarinette basse", "basse-guerrière", "clarinette basse", "basse-orgue"],
    "wclg": ["bathyphone", "batyphone"],
    "wclj": ["clarinetto piccolo"],
    "wcr": ["cromorne", "tournebout"],
    "wdb": ["contrebasson"],
    "wdu": ["dolçaine"],
    "weh": ["cor anglais", "taille de hautbois d'amour"],
    "wfa": ["flûte d'amour"],
    "wfg": ["flageolet"],
    "wfi": ["fifre"],
    "wfl": [
        "flûte",
        "flûte allemande",
        "flûte",
        "flûte d'allemagne",
        "flûte",
        "flûte traversière",
        "flûte",
        "traversière",
    ],
    "wflf": ["flûte basse"],
    "wga": ["galoubet", "flûte à trois trous", "galoubet", "flutet"],
    "wge": ["cor de chamois"],
    "wmo": ["orgue à bouche"],
    "wmu": ["musette"],
    "woa": ["hautbois d'amour"],
    "wob": ["hautbois", "haut-bois"],
    "wobe": ["heckelphone"],
    "wpi": ["piccolo", "petite flûte"],
    "wpo": ["bombarde", "chalemelle", "bombarde", "chalemie", "bombarde", "chalmeye"],
    "wpp": ["flûte de pan", "flûte pastorelle"],
    "wra": ["cervelas", "racquette"],
    "wre": [
        "flûte à bec",
        "flauste",
        "flûte à bec",
        "flaute",
        "flûte à bec",
        "flûte à neuf trous",
        "flûte à bec",
        "flûte d'angleterre",
    ],
    "wro": ["rothophone"],
    "wsa": [
        "saxophone",
        "ophicléide á clefs et á bec",
        "saxophone",
        "ophicléide á clefs",
    ],
    "wsn": ["surna"],
    "wsr": ["sarrusophone", "contrebasse à anche"],
    "wsu": ["courtaut", "sourdine"],
    "wun": ["bois"],
    "wun__y": ["bois - ethnique"],
    "wzz": ["bois - autre"],
    "zab": ["acrobate"],
    "zac": ["acteur enfant"],
    "zas": ["acteur muet"],
    "zat": ["acteur", "comédien"],
    "zaw": ["actrice", "comédienne"],
    "zda": ["danseur", "danseuse"],
    "zes": ["ingénieur du son"],
    "zju": ["jongleur"],
    "zmi": ["mime"],
    "zwp": ["figurant"],
    "zzz": ["interprète - autre"],
}

mimo = {
    "5639": ["Zang", "Zang (cymbale)"],
    "2419": ["Washint", "Washint (cloche)"],
    "3305": ["Vielle à roue", "Vielle à clavier"],
    "5649": ["Vase à percussion", "Vase acoustique"],
    "2227": ["UPIC", "Unité polyagogique informatique du CEMAMU"],
    "2760": ["Tar", "Tar (tambour)"],
    "2734": ["Tambourin à cordes", "Tambourin de Gascogne"],
    "2734": ["Tambourin à cordes", "Tambourin de Béarn"],
    "2887": ["Timbale", "Tambour sur cuvette"],
    "2617": ["Tambour en sablier", "Tambour sablier"],
    "2612": ["Tambour en gobelet", "Tambour gobelet"],
    "2504": ["Tambour tonneau", "Tambour en tonnelet"],
    "2504": ["Tambour tonneau", "Tambour en tonneau"],
    "2780": ["Trong com", "Tambour de riz"],
    "2730": ["Tambour à fente", "Tambour de bois"],
    "2734": ["Tambourin à cordes", "Tambour de Béarn"],
    "2585": ["Tambour", "Tambour d'orchestre"],
    "2978": ["Tambour métallique", "Tambour d'acier"],
    "2390": ["Sonnaille", "Sonnailles"],
    "2999": ["Semantron", "Simandre"],
    "2952": ["Lithophone", "Pierre sonore"],
    "2273": ["Pianos", "Pianofortes"],
    "2302": ["Pianoharpe", "Piano harpe"],
    "2952": ["Lithophone", "Phonolithe"],
    "3586": ["Pardessus de viole", "Pardessus de viole de gambe"],
    "5769": ["Orgue de chambre", "Orgue de salon"],
    "2937": ["Marimba", "Marimba (lamellaphone)"],
    "2930": ["Lamellaphone", "Languettophone"],
    "2930": ["Lamellaphone", "Lamellophone"],
    "2475": ["Kartal", "Kartal (cymbales)"],
    "2429": ["Khartal", "Kartal (claquettes)"],
    "2886": ["Kara", "Kara (timbale)"],
    "4838": ["Idiophone frotté", "Idiophone à friction"],
    "3007": ["Aeoliphone", "Éoliphone"],
    "3007": ["Aeoliphone", "Eoliphone"],
    "3020": ["Dibu dimbwa", "Dibu dimbwa (hochet)"],
    "2396": ["Dibu dimbwa", "Dibu dimbwa (cloche)"],
    "2470": ["Crotales", "Crotale"],
    "2529": ["Conga", "Congas"],
    "2439": ["Sinh tien", "Cliquette à sapèques"],
    "2244": ["Clavicythérium", "Clavecin vertical"],
    "4851": ["Cimta", "Cimta (claquettes)"],
    "6273": ["Ching", "Ching gong"],
    "2462": ["Ching", "Ching (cymbale)"],
    "3305": ["Vielle à roue", "Chifonie"],
    "2993": ["Tube à percussion", "Bâton-pilon"],
    "4093": ["Flûte traversière"],
    "3237": ["Guitare", "Guitares"],
    "2299": ["Piano"],
    "3573": ["Violon", "Violons"],
    "3226": ["Banjo", "Banjos", "banjo", "banjos"],
    "4164": ["Hautbois"],
    "3836": ["Clarinette", "Clarinettes"],
    "2266": ["Orgue", "Orgues"],
    "3561": ["Alto", "Altos"],
    "3582": ["Violoncelle", "Violoncelles"],
    "2251": ["Clavecin", "Clavecins"],
    "4096": ["Flûte à bec alto"],
    "3795": ["Basson"],
    "3585": ["Baryton"],
    "3111": ["Contrebasse", "Contrebasses"],
    "3736": ["Accordéon diatonique"],
    "3955": ["Flûte", "Flûtes"],
    "4039": ["Flûte à bec"],
    "3918": ["Flûte à bec soprano"],
    "3732": ["Accordéon"],
    "4118": ["Cor"],
    "3832": ["Clarinette basse"],
    "4342": ["Saxophone alto"],
    "4446": ["Trompette", "Trompettes"],
    "2985": ["Vibraphone"],
    "2968": ["Glockenspiel"],
    "2420": ["Castagnettes"],
    "2729": ["Caisse claire"],
    "2319": ["Orgue électronique"],
    "2235": ["Harmonium"],
    "4377": ["Trompette basse"],
    "4346": ["Saxophone", "Saxophones"],
    "4369": ["Trombone", "Trombones"],
    "4197": ["Cor anglais"],
    "4349": ["Saxophone ténor"],
    "3285": ["Harpe"],
    "3394": ["Luth"],
    "3598": ["Contrebasse de viole"],
    "3604": ["Basse de viole"],
    "4344": ["Saxophone basse"],
    "4029": ["Flûte piccolo"],
    "4024": ["Flûte de Pan"],
    "4347": ["Saxophone soprano"],
    "2506": ["Grosse caisse"],
    "2321": ["Synthétiseur"],
    "3510": ["Mandoline"],
    "2820": ["Gong"],
    "4467": ["Tuba"],
    "4362": ["Trombone basse"],
    "4327": ["Saxhorn basse"],
    "5702": ["Batterie"],
    "3633": ["Cymbalum"],
    "3609": ["Violone"],
    "3286": ["Harpe celtique"],
    "4368": ["Trombone ténor"],
    "4459": ["Tuba basse"],
    "3804": ["Contrebasson"],
    "3834": ["Cor de basset"],
    "4086": ["Flûte à bec ténor"],
    "4111": ["Harmonica"],
    "3473": ["Théorbe"],
    "3898": ["Flûte à bec basse"],
    "3099": ["Xylophone"],
    "3594": ["Dessus de viole"],
    "3591": ["Ténor de viole"],
    "3828": ["Clarinette alto"],
    "3839": ["Clarinette contrebasse"],
    "4326": ["Saxhorn baryton"],
    "3230": ["Guitare basse"],
    "4343": ["Saxophone baryton"],
    "3258": ["Kora"],
    "3236": ["Guitare électrique", "Guitares électriques"],
    "3729": ["Cithare"],
    "4462": ["Tuba contrebasse"],
    "3868": ["Cornet à bouquin"],
    "6538": ["Violoncelle piccolo"],
    "3881": ["Bugle"],
    "3820": ["Clairon basse"],
    "3822": ["Clairon"],
    "2783": ["Tumba"],
    "2268": ["Orgue positif"],
    "4463": ["Euphonium"],
    "3250": ["Ukulele"],
    "2354": ["Autres instruments"],
    "2347": ["Mirlitons"],
    "2230": ["Instruments à clavier"],
    "2208": ["Instruments électroniques"],
    "2205": ["Eléments d'instruments de musique"],
    "4475": ["Instruments mécaniques"],
    "3730": ["Instruments à vent"],
    "3101": ["Instruments à cordes"],
    "2370": ["Instruments à percussion"],
    "2206": ["Archets"],
    "6067": ["Embouchures"],
    "6068": ["Baguettes"],
    "6070": ["Plectres"],
    "2207": ["Archet"],
    "2209": ["Electroniques"],
    "2226": ["Trautonium"],
    "2219": ["Ondioline"],
    "2225": ["Theremin"],
    "6619": ["Assemblage de modules électroniques"],
    "2215": ["Mellotron"],
    "2217": ["Ondes Martenot"],
    "2211": ["Clavioline"],
    "6617": ["Accord guitar"],
    "6618": ["Accordéon-synthetiseur"],
    "6118": ["Guitare MIDI"],
    "5903": ["Croix sonore"],
    "2213": ["Gmebogosse"],
    "2214": ["Heliophon"],
    "2210": ["Boite à rythmes"],
    "2212": ["Gmebaphone"],
    "2229": ["Violon MIDI"],
    "2223": ["Solovox"],
    "2224": ["Telharmonium"],
    "2221": ["Sackbut"],
    "2222": ["Sampler"],
    "2216": ["Instrument MIDI"],
    "2220": ["Pianoline"],
    "4977": ["Vocoder"],
    "2270": ["Autres"],
    "2239": ["Clavecins"],
    "2231": ["Clavicordes"],
    "4479": ["Mécaniques"],
    "2316": ["Synthétiseurs"],
    "2264": ["Orgues"],
    "2233": ["Harmoniums"],
    "2232": ["Clavicorde"],
    "6147": ["Orgue-clavicorde"],
    "2234": ["Harmonicorde"],
    "2236": ["Poikilorgue"],
    "5767": ["Orgue expressif"],
    "6643": ["Claviphone"],
    "6652": ["Harmoniphone"],
    "6674": ["Harmonium à bouche"],
    "6691": ["Tonoscope-harmonium"],
    "6543": ["Physharmonica"],
    "2237": ["Régale"],
    "2257": ["Virginale"],
    "2256": ["Epinette"],
    "2241": ["Clavecin brisé"],
    "6542": ["Virginal double"],
    "2253": ["Clavecin-luth"],
    "2254": ["Muselaar"],
    "2250": ["Clavecin électrique"],
    "2252": ["Clavecin à maillets"],
    "2246": ["Clavecin organisé"],
    "2249": ["Clavecin numérique"],
    "2243": ["Clavecin oculaire"],
    "2240": ["Arpicordo"],
    "2260": ["Piano mécanique"],
    "6653": ["Harmonium-orgue"],
    "6635": ["Orgue de cabinet"],
    "5770": ["Orgue hydraulique"],
    "2265": ["Orgue éolien"],
    "2267": ["Orgue portatif"],
    "2269": ["Pyrophone"],
    "6705": ["Pianino"],
    "6548": ["Melodion"],
    "6544": ["Klavizilinder"],
    "6546": ["Glockenspiel à clavier"],
    "2272": ["Lyricorde"],
    "2271": ["Archiquier"],
    "4969": ["Terpodion"],
    "6717": ["Streichklavier"],
    "6141": ["Piano quatuor"],
    "2284": ["Piano à queue"],
    "2293": ["Piano à pédalier"],
    "2308": ["Piano carré"],
    "2311": ["Piano droit"],
    "2297": ["Piano organisé"],
    "2298": ["Piano table"],
    "6148": ["Harmonium-piano"],
    "2306": ["Piano pyramidal"],
    "2310": ["Piano à tangentes"],
    "2301": ["Piano-guitare"],
    "2289": ["Piano orgue"],
    "2290": ["Orphica"],
    "2286": ["Piano lyre"],
    "2287": ["Melopiano"],
    "2296": ["Piano éolien"],
    "2291": ["Pianet"],
    "2292": ["Pianino"],
    "2278": ["Piano console"],
    "2279": ["Piano numérique"],
    "2276": ["Claviharpe"],
    "2277": ["Clavi-lame"],
    "2283": ["Piano girafe"],
    "2285": ["Lutheal"],
    "2281": ["Piano électrique"],
    "2282": ["Euphonicon"],
    "2274": ["Piano automatique"],
    "2275": ["Piano cabinet"],
    "6713": ["Nähtischklavier"],
    "6714": ["Piano oblique"],
    "6712": ["Cembalet"],
    "5726": ["Sostenente piano"],
    "2320": ["Synclavier"],
    "2318": ["Orgue électrique"],
    "2317": ["Buchla"],
    "2348": ["Mirlitons"],
    "2352": ["Mirliton"],
    "2353": ["Nyastaranga"],
    "2349": ["Flûte eunuque"],
    "2351": ["Kazoo"],
    "2355": ["Autres"],
    "2362": ["Mattauphone"],
    "2364": ["Glass harmonica"],
    "2358": ["Cristal Baschet"],
    "2361": ["Jaltarang"],
    "2369": ["Violon de fer"],
    "6649": ["Fusu de nuxi"],
    "6547": ["Klaxon"],
    "6403": ["Carapace de tortue"],
    "4932": ["Dulcitone"],
    "4769": ["Crystallophone"],
    "2368": ["Scie musicale"],
    "2359": ["Glace-chord"],
    "6404": ["Effet du galop de cheval"],
    "2451": ["Cymbales"],
    "2912": ["Lamellophones"],
    "2861": ["Guimbardes"],
    "2879": ["Timbales"],
    "2807": ["Gongs"],
    "2424": ["Claquettes"],
    "3062": ["Xylophones"],
    "2805": ["Gamelan"],
    "2949": ["Lithophones"],
    "2988": ["Autres"],
    "3010": ["Crécelles"],
    "2965": ["Métallophones"],
    "3012": ["Hochets"],
    "3047": ["Râcloirs"],
    "2870": ["Grelots"],
    "2493": ["Tambours"],
    "2371": ["Cloches"],
    "2687": ["Ngonge"],
    "2415": ["Clochette de traîneau"],
    "2416": ["Cloche tubulaire"],
    "2408": ["Kin (cloche)"],
    "2410": ["Mbombu"],
    "2397": ["Dibu dinganga"],
    "2407": ["Kili"],
    "2395": ["Dibu"],
    "2387": ["Carillon"],
    "2381": ["Cloche"],
    "2384": ["Bozhong"],
    "2376": ["Ambassa"],
    "2377": ["Aporo"],
    "2372": ["Abanangbweli"],
    "6622": ["Carillon électrique"],
    "6796": ["Chung"],
    "6666": ["Ling"],
    "6318": ["Bol musical"],
    "6274": ["Cai tiu"],
    "6268": ["Ceinture à grelots"],
    "6651": ["Gshang"],
    "6364": ["Zang"],
    "5387": ["Tribu"],
    "5700": ["Tambour de bois"],
    "5686": ["Cloche simple"],
    "5655": ["Nzunzun"],
    "5508": ["Klentong"],
    "5503": ["Wadjira"],
    "5139": ["Agongon"],
    "4864": ["Ghungru"],
    "4660": ["Apertintaille"],
    "4887": ["Semakkalam"],
    "5185": ["Dawuro"],
    "2413": ["P'yonjong"],
    "2417": ["T'ukchong"],
    "2406": ["Hansho"],
    "2409": ["Lawle"],
    "2403": ["Ghanta"],
    "2404": ["Clochette"],
    "2400": ["Dril-bu"],
    "2401": ["Ekiro"],
    "2389": ["Cencerro"],
    "2399": ["Dotaku"],
    "2378": ["Banka"],
    "2382": ["Pien-chung"],
    "2373": ["Agogo"],
    "6993": ["Zan"],
    "5498": ["Cloche double"],
    "5491": ["Ushinarashi"],
    "5476": ["Gentorak"],
    "5382": ["Yinqing"],
    "5356": ["Skrabalas"],
    "5263": ["Klengkleng"],
    "5728": ["Windbell"],
    "2411": ["Nzoro"],
    "2421": ["Cap ke"],
    "2423": ["Castagnettes"],
    "5244": ["Kalenang"],
    "5367": ["Tajeraste"],
    "2436": ["Shkashek"],
    "2444": ["Fouet"],
    "2430": ["Paiban"],
    "2426": ["Claquettes"],
    "2428": ["Gandi"],
    "2425": ["Bones"],
    "4951": ["Phach"],
    "4923": ["Chlefeli"],
    "2445": ["Yotsudake"],
    "2447": ["Zhong"],
    "2442": ["Toka"],
    "2443": ["Walet-hkok"],
    "2435": ["Shakubyoshi"],
    "2433": ["Pak"],
    "2434": ["Scabellum"],
    "2427": ["Claquoir"],
    "6786": ["Kasik"],
    "6787": ["Cuillères"],
    "6636": ["Cai ban nhac"],
    "6322": ["Sanh"],
    "6267": ["Batte d'arlequin"],
    "5513": ["Kemanak"],
    "5386": ["Va let kyot"],
    "5342": ["Sanqioban"],
    "5317": ["Palipal"],
    "5225": ["Grap saypha"],
    "4885": ["Phal"],
    "4819": ["Claquoir à marteau"],
    "4821": ["Matraqueta"],
    "4663": ["Knaptand"],
    "4665": ["Troccola"],
    "4661": ["Capra"],
    "4662": ["Hanske knap"],
    "4581": ["Matraca"],
    "2488": ["Cymbale sizzle"],
    "2489": ["Cymbale sock"],
    "2476": ["Kasat"],
    "2480": ["Sajat"],
    "2471": ["Cymbales"],
    "2467": ["Cymbale choke"],
    "2469": ["Cymbale crash"],
    "2454": ["Chabara"],
    "2460": ["Chap"],
    "2452": ["Bo"],
    "6681": ["Penzhong"],
    "2482": ["Sanj"],
    "2484": ["Sbub-chal"],
    "2478": ["Manjira"],
    "2479": ["Rol-mo"],
    "2472": ["Dobatsu"],
    "2468": ["Chum choe"],
    "2492": ["Zil"],
    "2487": ["Sil-snyan"],
    "2490": ["Ting-ting-shags"],
    "5489": ["Silnen"],
    "5372": ["Talam"],
    "5365": ["Tah"],
    "5243": ["Kangsi"],
    "4930": ["Dobachi"],
    "4880": ["Mandira"],
    "5242": ["Jhalica"],
    "5366": ["Tahca"],
    "5351": ["Sichyah"],
    "5334": ["Rincik"],
    "5424": ["Bhusyah"],
    "5384": ["Than lvin"],
    "5506": ["Kecer"],
    "2524": ["Changgo"],
    "2532": ["Tambour cylindrique"],
    "2508": ["Bendir"],
    "2517": ["Tambour de bronze"],
    "2548": ["Damaru"],
    "2552": ["Daph"],
    "2533": ["Daf"],
    "2536": ["Daire"],
    "2497": ["Bajiao gu"],
    "2498": ["Ban"],
    "2507": ["Bata"],
    "2501": ["Bangu"],
    "2610": ["Glaw ng yao"],
    "2611": ["Go"],
    "2602": ["Ganga"],
    "2606": ["Gaza"],
    "2656": ["Kiringi"],
    "2670": ["Mazhar"],
    "2640": ["Kabaro"],
    "2652": ["Kendang"],
    "2573": ["Dholak"],
    "2581": ["Djoungdjoung"],
    "2554": ["Darabukka"],
    "2572": ["Dhol"],
    "2596": ["Engalabi"],
    "2598": ["Tambour sur cadre"],
    "2586": ["Duff"],
    "2595": ["Ekole"],
    "2714": ["Riqq"],
    "2728": ["Shagu"],
    "2744": ["Tambora"],
    "2746": ["Tambourin"],
    "2738": ["Tabl"],
    "2743": ["Tama"],
    "2682": ["Ngoma"],
    "2673": ["Mokita"],
    "2678": ["Mukupiela"],
    "2704": ["Pambai"],
    "2712": ["Redap"],
    "2688": ["Nkoko"],
    "2697": ["Nonga"],
    "2799": ["Zarb"],
    "2790": ["Uganda drum"],
    "2794": ["Wankara"],
    "2762": ["Tarol"],
    "2766": ["Tebashul"],
    "2752": ["Tambour sur fût"],
    "2777": ["Tomba"],
    "2787": ["Tyepondo-pinge"],
    "2768": ["Temple block"],
    "2769": ["Caisse roulante"],
    "6269": ["Bibliku"],
    "6294": ["Garamut"],
    "6308": ["Lali"],
    "6328": ["Trong chien"],
    "6329": ["Trong manh"],
    "6326": ["Trong boc"],
    "6327": ["Trong cai"],
    "6332": ["Tuvung"],
    "6330": ["Trong va"],
    "6331": ["Tunkul"],
    "6324": ["Tien-kou"],
    "6325": ["Trong"],
    "6366": ["Pan-kou"],
    "6365": ["Zirbaghali"],
    "6540": ["Tom-tom"],
    "6631": ["Tambour automatique"],
    "6684": ["Roto-toms"],
    "6797": ["Dadabuan"],
    "4578": ["Caja"],
    "4585": ["Lppumin"],
    "4586": ["Pandereta"],
    "4583": ["Kultrun"],
    "4584": ["Llamador"],
    "4577": ["Bombo"],
    "4597": ["Tlalpanhuetlhuetl"],
    "4588": ["Tambor mayor"],
    "4589": ["Teponaztli"],
    "4680": ["Diplipito"],
    "4685": ["Partrijzenlokker"],
    "4686": ["Pignata"],
    "4682": ["Duba"],
    "4684": ["Fanfrnoch"],
    "4693": ["Tambourin florentin"],
    "4695": ["Tümïr"],
    "4688": ["Rommelpot"],
    "4690": ["Bourdon"],
    "4699": ["Zambomba"],
    "4698": ["Wawa"],
    "4872": ["Joraghai"],
    "4869": ["Jagajhampa"],
    "4878": ["Madar"],
    "4857": ["Dindimi"],
    "4866": ["Gummati"],
    "4868": ["Hudukka"],
    "4884": ["Panaba"],
    "5137": ["Gu"],
    "5157": ["Bommaa"],
    "5181": ["Contra surdo"],
    "5175": ["Ciblon"],
    "5221": ["Gongand"],
    "5220": ["Gimbar"],
    "5259": ["Ketipung"],
    "5260": ["Khaijari"],
    "5256": ["Kenang"],
    "5299": ["Nodo"],
    "5300": ["Nyamalwa"],
    "5284": ["Libbit"],
    "5278": ["Kvakhica"],
    "5336": ["Repinique"],
    "5368": ["Tajeraste"],
    "5369": ["Tambor"],
    "5378": ["Tapattai"],
    "5381": ["Zambola"],
    "5361": ["Soge"],
    "5509": ["Gordang"],
    "5692": ["Tambour d'eau"],
    "5693": ["Tambour en vase"],
    "5735": ["Ditumba"],
    "5690": ["Tambour biconique"],
    "5691": ["Tambour cylindro-conique"],
    "6055": ["Tambour hochet"],
    "6120": ["Atwereba"],
    "6121": ["Jevetya"],
    "6124": ["Ngoma za muheme"],
    "6125": ["Woka"],
    "6122": ["Klakacki"],
    "6123": ["Laiyant"],
    "2514": ["Bodhran"],
    "2515": ["Bongos"],
    "2494": ["Adufe"],
    "2495": ["Agual"],
    "2531": ["Tambour conique"],
    "2535": ["Dagu"],
    "2528": ["Chwago"],
    "2564": ["Def"],
    "2567": ["Dhak"],
    "2551": ["Dap"],
    "2561": ["Davul"],
    "2519": ["Burczybas"],
    "2520": ["Cajon"],
    "2516": ["Bonko"],
    "2518": ["Buhai"],
    "2526": ["Cholgo"],
    "2527": ["Chunggo"],
    "2521": ["Cenda"],
    "2525": ["Chingo"],
    "2603": ["Garawung"],
    "2605": ["Gata-bere"],
    "2600": ["Furitsuzumi"],
    "2601": ["Gakudaiko"],
    "2615": ["Herrazi"],
    "2607": ["Gendang"],
    "2609": ["Ghata"],
    "2584": ["Donno"],
    "2570": ["Dhimay"],
    "2579": ["Djembe"],
    "2597": ["Fodrahi"],
    "2599": ["Tambour à friction"],
    "2588": ["Duma"],
    "2590": ["Dumbelek"],
    "2642": ["Kalangu"],
    "2646": ["Kalgo"],
    "2636": ["Ka"],
    "2641": ["Kakko"],
    "2650": ["Kelei"],
    "2653": ["Khanjari"],
    "2647": ["Kamango"],
    "2649": ["Kanjira"],
    "2622": ["Huaigu"],
    "2623": ["Huangnigu"],
    "2620": ["Huagu"],
    "2631": ["Huruk"],
    "2632": ["Idakka"],
    "2626": ["Hudko"],
    "2627": ["Huolang gu"],
    "2672": ["Milavu"],
    "2674": ["Mokugyo"],
    "2668": ["Luogu"],
    "2671": ["Mbejn"],
    "2679": ["Muyu"],
    "2681": ["Nangara"],
    "2675": ["Mokusho"],
    "2676": ["Mrdanga"],
    "2658": ["Kong"],
    "2659": ["Kon'go"],
    "2654": ["Khol"],
    "2655": ["Kidi"],
    "2665": ["Kyobanggo"],
    "2666": ["Kyondo"],
    "2661": ["Kotsuzumi"],
    "2664": ["Kwelli"],
    "2717": ["Rnga"],
    "2718": ["Sabaro"],
    "2708": ["Pu-ti-pu"],
    "2710": ["Rammana"],
    "2724": ["Sambhor"],
    "2726": ["Sgar dham"],
    "2720": ["Sakara"],
    "2721": ["Sakko"],
    "2698": ["Odaiko"],
    "2700": ["Otsuzumi"],
    "2689": ["Nkumvi"],
    "2690": ["Nogo"],
    "2706": ["Pandeiro"],
    "2707": ["Puk"],
    "2701": ["O-zi"],
    "2703": ["Pakhavaj"],
    "2772": ["Thon"],
    "2775": ["Timila"],
    "2764": ["Tbel"],
    "2770": ["Terbang"],
    "2782": ["Tsuridaiko"],
    "2779": ["Trong chau"],
    "2741": ["Taiko"],
    "2745": ["Tambourin de Provence"],
    "2732": ["Sogo"],
    "2757": ["Taogu"],
    "2759": ["Tapan"],
    "2750": ["Tamburu"],
    "2756": ["Tanggu"],
    "2798": ["Yonggo"],
    "2804": ["Zhangu"],
    "2788": ["Uchiwadaiko"],
    "2789": ["Udukku"],
    "2784": ["Tumbadora"],
    "2785": ["Tuntui"],
    "2796": ["Yaogu"],
    "2797": ["Yondo"],
    "2791": ["Unggo"],
    "2793": ["Tambour d'aisselle"],
    "4855": ["Davandai"],
    "4860": ["Dukkar"],
    "4678": ["Bubanj"],
    "4691": ["Tamboril"],
    "4904": ["Rabaga"],
    "4919": ["Bedug"],
    "4917": ["Atumpan"],
    "4886": ["Pirai"],
    "4867": ["Halgi"],
    "4947": ["Mo"],
    "4970": ["Thod-rnga"],
    "4971": ["Togo"],
    "4950": ["Ntenga"],
    "4931": ["Dogdog"],
    "4928": ["Cununo"],
    "4945": ["Madal"],
    "5000": ["Henggelege"],
    "5010": ["San-no-tsuzumi"],
    "4975": ["Waldteufel"],
    "4994": ["Chaozhou-biangu"],
    "5146": ["Audh"],
    "5159": ["Brekete"],
    "5162": ["Caixa"],
    "5014": ["Tai ping gu"],
    "5011": ["Shimedaiko"],
    "5013": ["Shugu"],
    "5142": ["Apentemma"],
    "5145": ["Atamo"],
    "5138": ["Adedemma"],
    "5201": ["Ese"],
    "5189": ["Fontomfrom"],
    "5190": ["Dhimayca"],
    "5211": ["Genderang"],
    "5215": ["Ghaval"],
    "5207": ["Gandang"],
    "5208": ["Geduk"],
    "5182": ["Dabadaba"],
    "5183": ["Daluka"],
    "5187": ["Dhah"],
    "5188": ["Dohol"],
    "5186": ["Debakan"],
    "5272": ["Kulanter"],
    "5279": ["Lalakhi"],
    "5216": ["Gimbal"],
    "5217": ["Gondang"],
    "5255": ["Kelmas"],
    "5258": ["Kete"],
    "5245": ["Kagan"],
    "5318": ["Penten"],
    "5319": ["Perng mang khok"],
    "5311": ["Pat waing"],
    "5312": ["Pati"],
    "5292": ["Mgba"],
    "5291": ["Medium"],
    "5309": ["Pat"],
    "5310": ["Pat mah"],
    "5307": ["Pachima"],
    "5410": ["Taphon"],
    "5426": ["Kantamdabadaba"],
    "5411": ["Atsimewu"],
    "5416": ["Bofu"],
    "5370": ["Tamborim"],
    "5371": ["Tamale"],
    "5362": ["Sulibao"],
    "5363": ["Surdo"],
    "5379": ["Tapon mon"],
    "5380": ["Ukom"],
    "5493": ["Tabla tarang"],
    "5507": ["Kao-kao"],
    "5510": ["Mokko"],
    "5470": ["Kundu"],
    "5442": ["Naykhim"],
    "5459": ["Thod dam"],
    "5480": ["Kroboto"],
    "5481": ["Krobotzi"],
    "5474": ["Conka"],
    "5720": ["Tambour à tension variable"],
    "5638": ["Mbonda"],
    "5521": ["Zaogu"],
    "6558": ["Tambour pincé"],
    "6936": ["Aki"],
    "6937": ["Akilwa"],
    "6965": ["Gangât"],
    "6967": ["Goilbi"],
    "6957": ["Gangango"],
    "6962": ["Gangari"],
    "6971": ["Guagulu"],
    "6974": ["Gubié"],
    "6968": ["Gongon"],
    "6970": ["Gouagnon"],
    "6946": ["Biô"],
    "6947": ["Dangossènè"],
    "6942": ["Bendré"],
    "6945": ["Bérenté"],
    "6952": ["Dontoumon"],
    "6954": ["Eguan"],
    "6948": ["Dendene-sa"],
    "6950": ["Djolon"],
    "6990": ["Lunga"],
    "6991": ["Minigé"],
    "6987": ["Palandan"],
    "6988": ["Lonlonga"],
    "6992": ["Ndo"],
    "6981": ["Gussiné Bié"],
    "6982": ["Youba"],
    "6976": ["Gudolo"],
    "6978": ["Gufalo"],
    "6985": ["Téhindé"],
    "6986": ["Rabingo"],
    "6983": ["Tourou"],
    "6984": ["Tondôrou"],
    "2806": ["Gamelan"],
    "2808": ["Bonang"],
    "2809": ["Canh"],
    "2853": ["Waniguchi"],
    "2854": ["Yaoling"],
    "2821": ["Gong ageng"],
    "2825": ["Jengglong"],
    "2816": ["Gan dham"],
    "2818": ["Gan tuc"],
    "2828": ["Kenong"],
    "2829": ["Ketuk"],
    "2826": ["Kasar"],
    "2827": ["Kempul"],
    "2814": ["Dan cong chien"],
    "2815": ["Dora"],
    "2811": ["Cong"],
    "2813": ["Daluo"],
    "2849": ["Tam am la"],
    "2851": ["Thanh la"],
    "2845": ["Soban"],
    "2846": ["Talempong"],
    "2856": ["Yunluo"],
    "2859": ["Zhengluo"],
    "2833": ["Kkwaenggwari"],
    "2835": ["Kyi-waing"],
    "2830": ["Khar-rnga"],
    "2831": ["Khong mong"],
    "2843": ["Nyo"],
    "2844": ["Shoko"],
    "2838": ["Luo"],
    "2842": ["Matsumushi"],
    "5512": ["Canang"],
    "5490": ["Suwukan"],
    "5511": ["Tawak"],
    "5209": ["Gangsa"],
    "5222": ["Goong"],
    "4995": ["Dscheng"],
    "5437": ["Maung-zaing"],
    "5383": ["Trompong"],
    "5479": ["Kemong"],
    "5477": ["Jing"],
    "5478": ["Kajar"],
    "5253": ["Kempyang"],
    "5254": ["Khong"],
    "5251": ["Kelenang"],
    "5252": ["Kempur"],
    "5290": ["Maung"],
    "6272": ["Bonang panerus"],
    "6270": ["Bonang barung"],
    "6271": ["Bonang panembung"],
    "6800": ["Tanggunggu"],
    "5285": ["Malamala"],
    "5274": ["Kulingtang"],
    "5327": ["Pong"],
    "5199": ["Engkuk"],
    "5200": ["Emong"],
    "5212": ["Gendingan"],
    "5421": ["Babendil"],
    "5409": ["Khawng"],
    "5502": ["Breng"],
    "4575": ["Ayotl"],
    "4813": ["Tamtam"],
    "2837": ["Kyi-zi"],
    "2865": ["Murcang"],
    "2864": ["Guimbarde"],
    "5265": ["Kubing"],
    "2862": ["Dan moi"],
    "2863": ["Genggong"],
    "2869": ["Tong"],
    "6143": ["Tombagl"],
    "6306": ["Komuz"],
    "6323": ["Susap"],
    "6675": ["Mukkuri"],
    "6793": ["Afiw"],
    "6794": ["Kinaban"],
    "5271": ["Kuding"],
    "4939": ["Karinding"],
    "5156": ["Bikong"],
    "5170": ["Cheng"],
    "4748": ["Kovïzh"],
    "4749": ["Marranzanu"],
    "4746": ["Drimba"],
    "4747": ["Drymba"],
    "2877": ["Châpeau chinois"],
    "2872": ["Grelots hit-hat"],
    "4751": ["Lozhky"],
    "2873": ["Grelot"],
    "2874": ["Nupur"],
    "2871": ["Chimta"],
    "2875": ["Suzu"],
    "2880": ["Baya"],
    "2882": ["Baz"],
    "2899": ["Tabla"],
    "2907": ["Tobol"],
    "2893": ["Nacaires"],
    "2894": ["Naqqara"],
    "2910": ["Tubilattes"],
    "4856": ["Dhanki"],
    "4858": ["Timbale double"],
    "4929": ["Daya"],
    "2904": ["Tasa"],
    "2906": ["Tikara"],
    "2884": ["Damaha"],
    "2885": ["Damau"],
    "2900": ["Tablak"],
    "2901": ["Tammatta"],
    "2890": ["Khurdak"],
    "2892": ["Nagara"],
    "5223": ["Gosha naghara"],
    "5277": ["Kvakhi"],
    "5375": ["Tamva"],
    "5339": ["Sangad"],
    "5408": ["Bülkül"],
    "4870": ["Jharidap"],
    "4859": ["Duggi"],
    "4854": ["Damama"],
    "4853": ["Dagara"],
    "4696": ["Tymbalon"],
    "2913": ["Bantyu"],
    "2916": ["Ikembe"],
    "2921": ["Kakolondondo"],
    "2923": ["Kalimba"],
    "2918": ["Ilimba"],
    "2919": ["Insimbi"],
    "2935": ["Madaku"],
    "2936": ["Madiumba"],
    "2933": ["Likembe"],
    "2940": ["Modeku"],
    "2941": ["Myonga"],
    "2939": ["Mbira"],
    "2945": ["Timbrh"],
    "2948": ["Tsimbi"],
    "2915": ["Dikembe"],
    "2920": ["Kadimba"],
    "2929": ["Kyanya"],
    "2938": ["Marimbula"],
    "2925": ["Kankobela"],
    "2927": ["Kisaanj"],
    "2942": ["Sanza"],
    "4839": ["Agbomboya"],
    "5264": ["Kondi"],
    "5418": ["Setinkane"],
    "7058": ["Kone"],
    "6642": ["Claviola"],
    "2955": ["P'yon'gyong"],
    "2950": ["Bianqing"],
    "2958": ["Qing"],
    "2963": ["T'ukkyong"],
    "2966": ["Bar-chime"],
    "2967": ["Glockenspiel de verre"],
    "2973": ["Saron barung"],
    "2974": ["Saron demung"],
    "2970": ["Lyra glockenspiel"],
    "2975": ["Saron panerus"],
    "2984": ["Tubaphone"],
    "4544": ["Enclume"],
    "5346": ["Saron peking"],
    "5347": ["Saron ricik"],
    "5248": ["Kenyir"],
    "5316": ["Penyacah"],
    "2972": ["Panghyang"],
    "2976": ["Slentem"],
    "2969": ["Kane"],
    "2971": ["Metallophone"],
    "2983": ["Thali"],
    "2977": ["Slento"],
    "4906": ["Gender"],
    "5766": ["Celesta"],
    "6660": ["Harpeal"],
    "6677": ["Ocleal"],
    "6680": ["Orpheal"],
    "5240": ["Jegogan"],
    "5247": ["Kantilan"],
    "5345": ["Saron"],
    "5348": ["Saron slentem"],
    "2998": ["Machine à pluie"],
    "3005": ["Triangle"],
    "2990": ["Flexatone"],
    "2989": ["Claves"],
    "6686": ["Idiophone frappé"],
    "6784": ["Ch'uk"],
    "6282": ["Duri dana"],
    "6309": ["Launut"],
    "6623": ["Percussion électronique"],
    "4835": ["Marteau"],
    "4836": ["Idiophone pincé"],
    "4834": ["Distinette"],
    "4876": ["Kashtha tarang"],
    "4863": ["Ghari"],
    "5659": ["Plaque sonore"],
    "5853": ["Récipient percuté"],
    "5385": ["Tintinca"],
    "5297": ["Mugu"],
    "5298": ["Ndingo"],
    "5315": ["Pattung"],
    "5152": ["Bantula"],
    "5149": ["Balingbing"],
    "5150": ["Bangibang"],
    "5505": ["Selokkat"],
    "5472": ["Bukhsa"],
    "5250": ["Kasuk"],
    "5226": ["Gumanak"],
    "5230": ["Hsaing-waing"],
    "4972": ["Toa"],
    "4960": ["Quitiplas"],
    "2991": ["Bâton à percussion"],
    "2995": ["Pi phat"],
    "3006": ["Txalaparta"],
    "3008": ["Zhu"],
    "3003": ["Shantu"],
    "3004": ["Tavoletta"],
    "2997": ["Pinpeat"],
    "4926": ["Cricri"],
    "3011": ["Crécelle"],
    "6695": ["Hochet globulaire"],
    "6676": ["Nhac"],
    "6827": ["Bâton de pluie"],
    "6798": ["Hochet sur bâton"],
    "6634": ["Cabaca"],
    "6281": ["Cimta"],
    "6142": ["Rangle"],
    "6266": ["Arbu"],
    "6321": ["Rin-no-tama"],
    "6307": ["Kulu"],
    "3045": ["Taga"],
    "3046": ["Wasamba"],
    "3041": ["Sesheh"],
    "3043": ["Swanga"],
    "3019": ["Azibwazi"],
    "3015": ["Assa muta chati"],
    "3017": ["Atamo"],
    "3013": ["Angklung"],
    "3014": ["Anzona"],
    "3037": ["Sanasel"],
    "3038": ["Sekere"],
    "3034": ["Qachel"],
    "3036": ["Hochet"],
    "3030": ["Legwegwe"],
    "3031": ["Maracas"],
    "3021": ["Ga"],
    "3022": ["Ifambu"],
    "4772": ["Bordon as ones"],
    "4871": ["Jhinka"],
    "4580": ["Cascabel"],
    "4624": ["Sonaja"],
    "4626": ["Wada"],
    "4621": ["Kanyahte'ka'nowa"],
    "4623": ["Katana"],
    "4620": ["Gurra"],
}
