work_names = {
    "_": [
        "Starmania",
        "l’ouverture de Don Giovanni",
        "la Symphonie fantastique",
        "la 5e Symphonie",
        "la 5eme symphonie",
        "la Symphonie n5",
        "symphonie n°5",
        "la 1ere symphonie",
        "la ballade des gens heureux",
        "Je t'aime, moi non plus",
        "la Lettre à Élise",
        "Parsifal"
        "à la cime d’un grand arbre",
        "les Nocturnes",
        "Hey Jude",
        "la pub CN",
        "la Chevauchée des Valkyries",
        "la Marche Impériale",
        "tireli",
        "la 9e Symphonie",
        "la Symphonie no 40",
        "Purple Rain",
        "la Symphonie inachevée",
        "la sonate pour piano n11",
        "la Donna e mobile",
        "générique de Colargol",
        "l'ageasse a fait son nid",
        "concerto pour piano 16",
        "requiem",
        "Wonderwall",
        "symphonie no 1",
        "Nocturnes, opus 9",
        "Études",
        "la Symphonie no 6",
        "la symphonie no 8",
        "Concertos brandebourgeois",
        "ave maria",
        "Fugue en sol mineur",
    ]
}