work_names = {
    "_": [
        "Starmania",
        "sacre du Printemps",
        "Sacre du printemps",
        "14e quatuor",
        "quatorzieme quatuor",
        "deuxieme quatuor",
        "neuvieme synphonie",
        "cinquieme synphonie",
        "3e quatuor",
        "quatuor 7",
        "don Giovanni",
        "Don Giovanni",
        "don giovan",
        "ouverture de la marche des Valkyries",
        "9e quatuor",
        "flûte enchantée",
        "flauto magico",
        "zauberflöte",
        "flauto magico",
        "flute enchantée",
        "Symphonie fantastique",
        "traviata",
        "Traviata",
        "gymnopédie",
        "Gymnopedies",
        "5e Symphonie",
        "quatuor no14",
        "quatuor n 10",
        "la 5eme symphonie",
        "5eme symphonie",
        "Symphonie n5",
        "symphonie n°5",
        "symphonie n° 5",
        "symphonie n° 9",
        "symphonie n° 3",
        "symphonie n° 7",
        "symphonie n°6",
        "symphonie n6",
        "symphonie n°9",
        "symphonie n9",
        "symphonie n°5",
        "David Bowie Anthology : Piano, vocal, guitar",
        "Space Oddity",
        "1ere symphonie",
        "1ere symphonie",
        "la ballade des gens heureux",
        "Je t'aime, moi non plus",
        "la Lettre à Élise",
        "Lettre à Élise",
        "Parsifal" "le Parsifal" "à la cime d’un grand arbre",
        "les Nocturnes",
        "Hey Jude",
        "la pub CN",
        "the entertainer",
        "entertainer",
        "Chevauchée des Valkyries",
        "Marche Impériale",
        "Marche Impériale",
        "tireli",
        "9e Symphonie",
        "9eme Symphonie",
        "la Symphonie no 40",
        "Purple Rain",
        "Symphonie inachevée",
        "sonate pour piano n11",
        "Donna e mobile",
        "générique de Colargol",
        "l'ageasse a fait son nid",
        "concerto pour piano 16",
        "requiem",
        "Wonderwall",
        "symphonie no 1",
        "Nocturnes, opus 9",
        "Études",
        "la Symphonie no 6",
        "la symphonie no 8",
        "Concertos brandebourgeois",
        "ave maria",
        "Fugue en sol mineur",
        #### EXPORTED FROM GRAPH
        "Children's Crusade. chirden's voices and orchestra. op. 82.",
        "Ouvertüre zum 'Fliegenden Holländer'. Quatuor à cordes.",
        "Preludes. 1. BWV 939. Do majeur.",
        "... quasi una fantasia.... piano et groupes d'instruments. Op. 27.",
        "... quasi una fantasia.../György Kurtag",
        "...Îles, rives...:Musique pour violon, choeur de chambre et orchestre",
        "...quasi una fantasia... (presque une fantaise):pour piano et groupes instrumentaux",
        "'...Zwei Gefühle...' Musik mit Leonardo/Helmut Lachenmann",
        " Maccabaeus. HWV 63. See, the conqu'ring hero comes. Violoncelle, piano. WoO 45. Sol majeur.",
        "Die Zauberflöte. KV 620. Ein Mädchen oder Weibchen. Violoncelle, piano. Op. 66. Fa majeur.",
        "Die Zauberflöte KV 620. Bei Männern, welche Liebe fühlen. Violoncelle, piano. WoO 46. Mi bémol majeur.",
        "Ich ruf' zu dir, Herr, BWV 639. Piano. BV B 27 no 5.",
        "Komm, Gott, Schöpfer, BWV 667. Piano. BV B 27 no 1.",
        "Nun freut euch, lieben Christen, BWV 734. Piano. BV B 27 no 4.",
        "Nun komm, der Heiden Heiland, BWV 659. Piano. BV B 27 no 3.",
        "Wachet auf, ruft uns die Stimme, BWV 645. Piano. BV B 27 no 2.",
        "10 pièces. Piano. Op. 24.",
        "12 [Douze] exercices mélodiques:pour flûte à bec soprano",
        "12 Allemandes. Piano. D 790. Op. posth. 171.",
        "12 études. Piano. CT 26-27-28-29-30-31-32-33-34-35-36-37. Op. 25.",
        "12 sonates en trio op.3, Nos. 10 à 12.:pour 2 violons et basse continue",
        "12 sonates en trio op.3, Nos. 4 à 6.:pour 2 violons et basse continue",
        "12 sonates en trio op.3, Nos. 7 à 9:pour 2 violons et basse continue",
        "12 sonates en trio op.3, Nos1 à 3.:pour 2 violons et basse continue",
        "15 [Quinze ]Danses paysanes hongroises:pour piano solo",
        "15 duos des 17ème et 18ème siècles:pour 2 flûtes à bec soprano",
        "18 [Dix-huit] Duos faciles:pour 2 flûtes",
        "2 csárdás. Piano. S 225.",
        "2 rhapsodies. Piano. Op. 79. si mineur, sol mineur.",
        "21 [Vingt-et-un] Duos faciles:pour deux flûtes",
        "21 duos d'après les '44 duos pour 2 violons':pour alto et violoncelle",
        "21 ungarische Tänze. Piano à quatre mains. WoO1.",
        "24 Caprices:pour violoncelle seul",
        "24 duos, 1er cahier (1 à 13):pour violon et violoncelle",
        "24 duos, 2e cahier (14 à 24):pour violon et violoncelle",
        "24 Duos, sur des thèmes des opéras 'La Flûte enchantée' et 'Don Juan':pour violon et alto",
        "2ème Quatuor, op.79, d'après le KV 374f:pour clarinette en Sib, violon, alto et violoncelle",
        "3 Canzonas instrumentales:pour 2 flûtes (ou 2 violons) et basse continue",
        "3 Ecossaises. Piano. no 1 à 3. CT 11-12-13. Op. 72 no 3.",
        "3 Miniatures:pour flûte et piano",
        "3 Ragtimes:pour flûte à bec et guitare",
        "3 Romances. Piano. Op. 21.",
        "3 valses. Piano. CT 212-213-214. Op. 64.",
        "30 [Trente] duos faciles autour de 1750:pour deux flûtes",
        "30 [Trente] duos faciles autour de 1800:pour deux flûtes",
        "30 [Trente] duos faciles autour de 1850:pour deux flûtes",
        "36 Originaltänze. Piano. D 365. Op. 9.",
        "3ème Quatuor, op.79, d'après le KV 496:pour clarinette en Do, violon, alto et violoncelle",
        "4 Impromptus. Piano. D 899. Op. 90.",
        "4 Mazurkas. Piano. no 22, 23, 24, 25. CT 72-73-74-75. Op. 33.",
        "40 études pour flûte à bec alto:d'après les solfèges de Fréderic le Grand",
        "6 Duos faciles, op. 18:pour 2 flûtes",
        "6ème sonate:version pour trompette, trombone et orgue",
        "73. Sonate en trio en Fa majeur:pour violon (ou flûte ou hautbois), viole de gambe ou alto et basse continue",
        "90ème Sonate en trio, en Mi mineur:pour flûte, hautbois (ou violon) et basse continue",
        "A deux:Musiques pour trompettes du 17e et 18e siècles",
        "A Foggy Day/George Gershwin",
        "ABC : Doigtés pour les gammes à l'accordéon:pour l'accordéon standard et l'instrument à basse mélodique",
        "Abdelazer. Z 570.",
        "Aïda",
        "Aïda.[(Opéra)]",
        "Ain't Misbehavin'",
        "Ain't misbehavin'.",
        "Airs de chambre pour flûte seule:un choix d'airs écossais, irlandais et gallois pour flûte à bec seule (ou flûte traversière ou violon)",
        "Airs pour violons:Musique irlandaise pour cordes",
        "Al desio di chi t'adora",
        "Al desio di chi t'adora. KV 577.",
        "Aladdin, op. 34",
        "Aladdin. op. 34.[(Musique de scène)]",
        "Album d'un voyageur",
        "Album d'un voyageur. Piano. S 156.",
        "Album de lieder pour la jeunesse, op. 79",
        "Album de Lieder pour les jeunes, d'après des poèmes de Heinrich Hoffmann von Fallersleben, op. 79:pour voix et piano (avec 2e et 3e voix), édition originale pour voix aigüe(s)",
        "Album de UE (Universal Editions) pour les jeunes pianistes.:Musique du 20e siècle",
        "Album pour les enfants, op. 39",
        "Aleko",
        "Aleko.[(Opéra;Opéras)]",
        "allegro:pour vibraphone et deux marimbas (ou trois marimbas)",
        "Aller-retour:sketch avec musique",
        "Alt-Wiener Tanzweisen",
        "Alt-Wiener Tanzweisen. Piano, violon.",
        "Amour digital:pour flûte et violon",
        "An der schönen blauen Donau. Op. 314.[(Valses de Vienne)]",
        "An ode on the death of Mr Henry Purcell.",
        "Andante et allegro vivace:pour deux clarinettes et piano (ad libitum)",
        "Angélique",
        "Angélique.[(Opéra;Opéras)]",
        "Années de pélerinage. Deuxième année : Italie",
        "Années de pélerinage. S. 161.. Deuxième année . Italie",
        "Après la transformation, tiré de la Grande Messe Allemande:pour cor, soprano ou flûte et orgue",
        "Arabeske. Piano. Op. 18.",
        "Arabesque, op. 18",
        "Arbre de Noël",
        "Arrangements libres, IIe volume:pour piano solo",
        "Arrangements libres, IVe volume:pour piano solo",
        "Arrangements libres, IXe volume:pour piano solo",
        "Arrangements libres, VIe volume:pour piano solo",
        "Arrangements libres, VIIe volume:pour piano solo",
        "Arrangements libres, VIIIe volume:pour piano solo",
        "Arrangements libres, Volume 20, Transcriptions V:pour piano solo",
        "Arrangements libres, XIe volume:pour piano solo",
        "Arrangements libres, XIIe volume:pour piano solo",
        "Arrangements libres, XIIIe volume:pour piano solo",
        "Arrangements libres, XIVe volume:pour piano solo",
        "Arrangements libres, XVe volume:pour piano solo",
        "As Time Goes By",
        "As time goes by.",
        "Atmosphères",
        "Atmosphères:pour grand orchestre",
        "Atmosphères.",
        "Atys",
        "Atys. LWV 53.[(Opéra)]",
        "Au bord de la mer, étude de concert:pour piano",
        "Ausklang",
        "Ausklang.",
        "Aux armes [mes] pensées!:Cantate pour soprano, trompette obligée et base continue",
        "Bagatelle ohne Tonart. Piano. S 216a.",
        "Bagatelle sans tonalité",
        "Bagatelles Op. 47:pour 2 violons, violoncelle et harmonium (ou piano)",
        "Bagatelles:pour flûte, contrebasse et piano",
        "Ballades de Jazz:16 ballades de jazz célébres",
        "Ballades et chansons, Livre I:pour voix et piano, voix grave.",
        "Barcarolle",
        "Barcarolles. Piano. CT 6. Op. 60.",
        "Béatrice et Bénédict, H 138",
        "Béatrice et Bénédict. H 138.[(Opéra)]",
        "Bellérophon",
        "Bellérophon. LWV 57.[(Opéra)]",
        "Benvenuto Cellini, H 76A",
        "Benvenuto Cellini. H 76A.[(Opéra)]",
        "Berceuse:pour piano",
        "Blackbird. Piano.",
        "Blackbird. Piano.",
        "Burlesque:pour piano et orchestre",
        "Cadences:pour trois percussionnistes",
        "Canon:pour 2 violes de gambe (ou violons ou flûtes) et basse continue",
        "Canon:pour trois violons et basse",
        "Cantabile",
        "Cantabile. Piano. CT 9. KK IV",
        "Cantate 'Je porterai ma croix avec joie':pour basse, choeur et orchestre de chambre",
        "Cantate BWV 18, pour le Sexagésime : 'Comme la pluie et la neige qui tombent du ciel'. Version de Leipzig.:pour solistes S,T et B, Choeur mixte SATB et ensemble instrumental",
        "Cantigas de Santa Maria",
        "Cantigas de Santa Maria.",
        "Canzona 8 dite 'La Rubina', à 3 voix, tirée de : Canzonas pour jouer à 1-4 voix et basse continue:pour 2 violons ou cornets à bouquin et basse continue",
        "Canzonas instrumentales:pour quatre voix (Flûtes à bec ou instruments de la renaissance)",
        "Canzonnnettes:pour 2 flûtes à bec sopranos ou flûtes à bec soprano et alto (ou 2 violons)",
        "Capriccio",
        "Capriccio. Piano et 6 instruments.",
        "Caprice:pour quatre instruments mélodiques (flûtes à bec, violons ou quatuor à cordes)",
        "Caprices, canzonas et sonates:pour 2, 3, 4 et 5 instruments, avec ou sans basse continue",
        "Carmina Burana",
        "Carmina burana.",
        "Carnaval de Venise:Chansons et danses à quatre voix de la période Médicis (flûtes à bec ou instruments de la Renaissance)",
        "Carré",
        "Carré. für 4 Orchester und 4 Chöre.",
        "Casse-Noisette",
        "Chaconnes:pour deux flûtes à bec (ou flûtes, ou violons) et basse continue",
        "Chanson du pays natal Op. 117:pour soprano, clarinette et piano",
        "Chansons enfantines hongroises:",
        "Chant du destin, op. 54",
        "Chant du destin:pour choeur et orchestre, réduction pour piano par le compositeur",
        "Chant funèbre, op. 5",
        "Chants et danses populaires:pour 2 ou 3 flûtes à bec (alto-ténor ou alto-alto-ténor, et multiples)",
        "Chants sacrés en honneur de Thomas Tallis:pour voix égales a cappella",
        "Children's corner",
        "Children's corner. Piano. FL 119.",
        "Cinq mazurkas Op. 7",
        "Cinq mazurkas Op. 7",
        "Cinq Méphisto-valses ; Méphisto Polka:pour piano",
        "Cinq Morceaux de fantaisie, Op.3",
        "Cinq petits préludes",
        "Cinq pièces de l'opus 22:pour 2 clarinettes, cor et basson",
        "Cinquante études pour percussion:pour 1 à 3 instrumentistes et groupes",
        "Cinquième sonate, en Sib Majeur:pour violon, viole de gambe (ou 2e. violon) et basse continue",
        "Cinquième sonate, tirée de La Cetra, Op.10 [2 versions : grave et aigue]:pour consort de 4 violes de gambe et basse continue",
        "Commencer à quatre:Premiers pas dans le jeu du quatuor à cordes",
        "Compositions [Pohádka, un conte ; Presto]:pour violoncelle et piano",
        "Concerti grossi. HWV 321. Op. 6 no 3. Mi mineur.",
        "Concerti grossi. HWV 328. Op. 6 no 10. Ré mineur.",
        "Concerto à 4 en La mineur:pour flûte à bec alto, hautbois (ou flûte à bec ténor ou violon), violon et clavecin (ou piano), violoncelle (ou viole de gambe) ad lib.",
        "Concerto comique no 7 en do mineur 'La Servante au bon tabac'",
        "Concerto comique. Ensemble instrumental. No 7. Do mineur. La Servante au bon tabac.",
        "Concerto en La Majeur, Musique de table N°1:pour flûte, violon, violoncelle, cordes et basse continue",
        "Concerto en mi bémol majeur:pour hautbois, cordes et basse continue",
        "Concerto en Ré mineur:pour clavecin et cordes, d'après J.S. Bach",
        "Concerto en sol mineur:pour clavecin et cordes",
        "Concerto en ut majeur:pour trompette, 3 hautbois, basson et basse continue",
        "Concerto grosso no 10 en ré mineur, op.6 no 10, HWV 328",
        "Concerto I, en La majeur:pour clavecin (orgue), deux violons et basse continue",
        "Concerto N°.1 en Ré mineur:pour clavecin et cordes",
        "Concerto N°.II en Mi Majeur:pour clavecin et cordes",
        "Concerto N°.III en Ré Majeur:pour clavecin et cordes",
        "Concerto N°.IV en La Majeur:pour clavecin et cordes",
        "Concerto N°V en Fa mineur:pour clavecin et cordes",
        "Concerto N°VI en Fa Majeur:pour clavecin, deux flûtes à bec et cordes",
        "Concerto pour clavecin et cordes en fa mineur BWV 1056",
        "Concerto pour clavecin et cordes en la majeur BWV 1055",
        "Concerto pour clavecin et cordes en mi majeur BWV 1053",
        "Concerto pour cor et petit orchestre:réduction pour piano",
        "Concerto pour deux pianos et orchestre, op. 88a",
        "Concerto pour flûte, orchestre à cordes et basse continue 'La tempesta di mare'",
        "Concerto pour piano et orchestre en fa dièse mineur, op. 20",
        "Concerto pour piano et orchestre en fa mineur n°2, opus 21:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Concerto pour piano et orchestre en la mineur, op. 16",
        "Concerto pour piano et orchestre no 2",
        "Concerto pour piano et orchestre, op. 42",
        "Concerto pour violon et orchestre",
        "Concerto pour violon et orchestre",
        "Concerto pour violon et orchestre à cordes 'Tala Gaisma'",
        "Concerto pour violon et orchestre en ré mineur",
        "Concerto pour violon, viole de gambe et orchestre:conducteur d'orchestre",
        "Concerto pour violon, viole de gambe et orchestre:réduction pour piano",
        "Concerto pour violoncelle",
        "Concerto:pour piano et orchestre",
        "Concertos. Clavecin, cordes, basse continue. BWV 1053. Mi majeur.",
        "Concertos. Clavecin, cordes, basse continue. BWV 1055. La majeur.",
        "Concertos. Clavecin, cordes, basse continue. BWV 1056. Fa mineur.",
        "Concertos. Cor, orchestre. Op. 91. Si bémol majeur.",
        "Concertos. Flûte, orchestre à cordes, basse continue. RV 433. Op. 10 no 1. Fa majeur.",
        "Concertos. Opus 88a. La bémol mineur.",
        "Concertos. Piano, orchestre. no 2. B 48. Op. 21. Fa mineur.",
        "Concertos. Piano, orchestre. Op. 16.",
        "Concertos. Piano, orchestre. Op. 20. Fa dièse mineur.",
        "Concertos. Piano, orchestre. Op. 42.",
        "Concertos. Violon, orchestre. No 1. Op. 26. Sol mineur.",
        "Concertos. Violon, orchestre. Op. 47. Ré mineur.",
        "Concertos. Violon, orchestre. Ré mineur.",
        "Concertos. Violoncelle, orchestre. Op. 85. Mi mineur.",
        "Correspondances",
        "Correspondances",
        "Correspondances.",
        "Correspondances.",
        "Csárdás macabre",
        "Csárdás macabre. Piano. S 224.",
        "Cycles:pour percussion (3 musiciens) et piano",
        "Cyprise. Quatuor à cordes. B 152.",
        "Dans la fôret, op.50:Suite pour violoncelle et piano",
        "Dans les brumes",
        "Danse du sauteur à cordes:pour violon et piano",
        "Danse:pour trio à cordes",
        "Danses du 16e siècle, d'après le collection de Pierre Phalèse, Anvers 1583:pour quatre voix",
        "Danses extraites de 'Terpsichore':pour cinq instruments",
        "Danses Hongroises Nos. 5 et 6:arrangement pour quatuor à cordes",
        "Danses hongroises Nos. 5 et 6:pour quatuor à cordes",
        "Danses populaires internationales:pour quatuor de flûtes à bec (guitare et percussion ad libitum)",
        "Danses roumaines N° 1 à 6:pour tuba et piano",
        "Danses slaves",
        "Danses slaves Op.74/1 à 4:pour orchestre",
        "Danses, une séléction:pour piano",
        "Das lange Weihnachtsmahl.[(Opéras)]",
        "De la maison des morts",
        "De la poésie populaire juive",
        "De la poésie populaire yiddish:cycle de chansons pour soprano, contralto et ténor avec accompagnement de piano",
        "De la poésie populaire yiddish:Cycle de mélodies pour soprano, contralto, ténor et piano",
        "Déclarations d'amour pour la flûte à bec basse:Quatre pièces pour flûte à bec basse et guitare",
        "Der Kaiser von Atlantis",
        "Der Kaiser von Atlantis. Op. 49.[(Opéra)]",
        "Der Rose Pilgerfahrt, op. 112.",
        "Der Tanz in der Dorfschenke. Piano. S 514.",
        "Detskiy al'bom. Piano. Op. 39.",
        "Deutsche Mottete. Chant. TrV 230. Op. 62.",
        "Deux csárdás",
        "Deux Duos Op.46:pour flûte et clarinette",
        "Deux duos op.6:pour violon et violoncelle",
        "Deux duos:pour hautbois et alto ou violoncelle",
        "Deux entrées:pour six instruments égaux",
        "Deux fables d'Ivan Krylov",
        "Deux Fables de Krylov, Opus 4:pour mezzo-soprano et piano (réduction de l'orchestre)",
        "Deux impressions, musique avec Leonardo:pour narrateurs et ensemble",
        "Deux légendes : Saint-François d'Assise, la prédication aux oiseaux. Saint François de Paule marchant sur les flots",
        "Deux légendes : Saint-François d'Assise, la prédication aux oiseaux. Saint François de Paule marchant sur les flots",
        "Deux nocturnes Op. 27",
        "Deux par deux:Duos de difficultés différentes pour flûte et clarinette",
        "Deux par deux:Duos progressifs pour bassons",
        "Deux Quatuors:pour hautbois, violon, alto et violoncelle",
        "Deux rhapsodies pour piano, op. 79",
        "Deux sonates, en do mineur et en sib majeur:pour flûte à bec alto (flûte) et basse continue",
        "Deux suites extraites de 'The Musick' Handmaid':pour flûte à bec soprano et piano",
        "Deuxième sonate en Mi mineur:pour violon, viole de gambe (ou 2e. violon) et basse continue",
        "Dichterliebe. Voix et piano. Op. 48.",
        "Die Dreigroschenoper.[(Opéra)]",
        "Die Entführung aus dem Serail. KV 384.[(Opera)]",
        "Die erste Walpurgisnacht. MWV D 3. Op. 60.[(Cantates)]",
        "Die Geschöpfe des Prometheus. Op. 43.[(Ballet)]",
        "Die Schöpfung. Orchestre. Hob XXI 2.",
        "Die sieben letzte Worte unseres Erlösers am Kreuze. Orchestre. Hob XX 1A.",
        "Die Zauberflöte. KV 620.[(Opera)]",
        "Diverses compositions pour piano:Nocturnes, Ecossaises, Impromptu en Do# mineur et autres",
        "Divertissement 'La clémence de Titus':pour trois cors de basset (deux clarinettes et basson ou trois clarinettes)",
        "Divertissement 'Les noces de Figaro':pour trois cors de basset (deux clarinettes et basson ou trois clarinettes)",
        "Divertissement:pour deux hautbois, deux clarinettes, deux bassons et deux cors",
        "Divertissement:pour trompette, trombone et piano",
        "Divertissements mélodieux:pour deux flûtes à bec ou flûtes traversières (violons) et basse continue",
        "Divertissements:pour piano (clavecin), deux violons et violoncelle",
        "divisions sur des basses obstinées:pour flûte à bec soprano et basse continue",
        "Dix marches pour rater la victoire:pour instruments à vent et percussions",
        "Dix pièces",
        "Dolly, op. 56",
        "Dolly. Orchestre. Op. 56.",
        "Don Carlos",
        "Don Carlos.[(Opéra;1867)]",
        "Don Giovanni. KV 527.[(Opera)]",
        "Don Giovanni",
        "Don Juan, KV 527",
        "Don Juan",
        "Douze airs de danse pour quatre instruments:quatuor de flûtes à bec, quatuor à cordes ou toute autre formation instrumentale",
        "Douze allemandes, D 790",
        "Douze chansons:pour quatre instruments ATTB",
        "Douze chorals choisis:pour quatuor de flûtes à bec",
        "Douze duos pour cors, KV 496a",
        "Douze études Op. 10",
        "Douze études Op.25",
        "Douze valses, dix-sept ländler et neuf écossaises, D 145",
        "Douze valses, dix-sept ländler et neuf écossaises, D 145",
        "Douze Variations pour violoncelle et piano sur le thème 'Ein Mädchen oder Weibchen' de La Flûte enchantée de Mozart op. 66",
        "Douze Variations pour violoncelle et piano sur le thème 'See the conquering hero comes' de l+oratorio de Haendel Judas Macchabée WoO 45",
        "Du berceau jusqu'à la tombe",
        "Du berceau jusqu'à la tombe:13è poème symphonique",
        "Duo en Fa Majeur:pour alto et violoncelle",
        "Duo en Ré Majeur:pour alto et violoncelle",
        "Duo en Sol Majeur:pour flûte et violon",
        "Duo:pour alto et violoncelle",
        "Duo:pour deux violes de gambe",
        "Duo:pour violon et violoncelle",
        "Duo:pour violon et violoncelle ou deux violons",
        "Duos faciles:pour deux flûtes",
        "Duos parisiens pour 2 violes de gambe : Cinquième Sonate ; Sixième Sonate:Six sonates pre-classiques d'un compositeur inconnu. Collection Vm7 6297 de la Bibliothèque Nationale de Paris.",
        "Duos parisiens pour 2 violes de gambe : Première Sonate ; Deuxième Sonate:Six sonates pre-classiques d'un compositeur inconnu. Collection Vm7 6297 de la Bibliothèque Nationale de Paris.",
        "Duos parisiens pour 2 violes de gambe : Trisième Sonate ; Quatrième Sonate:Six sonates pre-classiques d'un compositeur inconnu. Collection Vm7 6297 de la Bibliothèque Nationale de Paris.",
        "Duos pour deux violons:choisis et arrangés pour deux guitares",
        "Duos Royaux pour 2 violes de gambe:Cahier 1 : Sonates d'après Somis et Senaillé",
        "Duos Royaux pour 2 violes de gambe:Cahier 2 : Sonates d'après Joseph Bodin de Boismortier",
        "Duos Royaux pour 2 violes de gambe:Cahier 3 : Sonates d'après Joseph Bodin de Boismortier",
        "Duos Royaux pour 2 violes de gambe:Cahier 4 : Sonates d'après Corelli, Mascitti et Leclair",
        "Duos Royaux pour 2 violes de gambe:Cahier 5 : Sonates d'après Francesco Montanari, Jan-Baptiste Senaillé et Franz Benda",
        "Dve basni I. A. Krylova. Op. 4.",
        "Eglogues:pour deux hautbois et cor anglais",
        "Ein Heldenleben. TrV 190. Op. 40.",
        "Ein Sommernachtstraum von Shakespeare. MWV M 13. Op. 61.",
        "Eine kleine Nachtmusik. Violons (2), alto, violoncelle, contrebasse. KV 525.",
        "Eine kleine Nachtmusik. Violons (2), alto, violoncelle, contrebasse. KV 525.",
        "El amor brujo.[(Ballet)]",
        "El sombrero de tres picos. G 53.[(Ballet)]",
        "El sombrero de tres picos. G 53.[(Ballet)]",
        "Ellens Gesang III. Op.52 no 6.",
        "Espagne:Promenade pour quatuor ou orchestre à cordes",
        "Esprit rude",
        "Esprit rude",
        "Esprit rude, esprit doux",
        "Esprit rude, esprit doux 2",
        "Etudes opus 10, Nos. : 3, 5, 6, 8, 9, 10:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Etudes opus 25:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Etudes. Piano. CT 16. Op. 10 no 3. Mi majeur.",
        "Etudes. Piano. CT 17. Op. 10 no 4. Do dièse mineur.",
        "Etudes. Piano. CT 18. Op. 10 no 5. Sol bémol majeur.",
        "Etudes. Piano. CT 19. Op. 10 no 6. Mi bémol mineur.",
        "Etudes. Piano. CT 22. Op. 10 no 9. Fa mineur.",
        "Etudes. Piano. CT 23. Op. 10 no 10. La bémol majeur.",
        "Evocation à la Chapelle Sixtine",
        "Evocation à la Chapelle Sixtine. Piano. S 461.",
        "Exercices dans tous les tons pour la flûte à bec soprano:avec des pièces accompagnées par le piano",
        "Exercices pour le pouce:pour le violoncelle",
        "Exercices:pour accordéon à basses chromatiques",
        "oeuvres complètes : Danses, Marches et Scherzos:pour piano solo",
        "oeuvres complètes : Danses, Marches et Scherzos:pour piano solo",
        "oeuvres complètes : Etudes techniques I:pour piano solo",
        "oeuvres complètes : Etudes techniques II:pour piano solo",
        "oeuvres complètes : Oeuvres à caractère individuel I:pour piano solo",
        "oeuvres complètes : Versions pour le piano de ses propres oeuvres II:pour piano solo",
        "oeuvres complètes : Versions pour le piano de ses propres oeuvres III:pour piano solo",
        "oeuvres complètes : Versions pour le piano de ses propres oeuvres:pour piano solo",
        "Fantaisie",
        "Fantaisie 'Browning':pour cinq instruments",
        "Fantaisie 'Innsbruck ich muss dich lassen':pour cinq instruments",
        "Fantaisie en Do Majeur:pour violon et piano",
        "Fantaisie N°11 pour quatre voix:en quatre parties (SAAtB)",
        "Fantaisie op.28:pour piano",
        "Fantaisie pour violon et piano en do majeur, D 934",
        "Fantaisie-impromptu. Piano. CT 46. Op. 66. Do dièse mineur.",
        "Fantaisie-impromptu. Piano. CT 46. Op. 66. Do dièse mineur.",
        "fantaisie, opus 61:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Fantaisie:pour deux pianos",
        "Fantaisies. Piano. CT 42. Op. 49.",
        "Fantaisies. Piano. Op. 28. Si mineur.",
        "Fantaisies. Volume 1 : pour 3 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Fantaisies. Volume 2 : pour 4 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Fantaisies. Volume 3 : pour 4 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Fantaisies. Volume 4 : pour 4 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Fantaisies. Volume 5 : pour 3 à 5 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Fantaisies. Volume 6 : pour 5 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Fantaisies. Volume 7 : pour 6 voix:Edition complète des 42 fantaisies instrumentales (en 7 volumes) pour consort de 3 à 6 voix (violes ou bois)",
        "Festmarch zur GoetheJubiläumsfeier. Orchestre. S 115.",
        "Feu d'artifice, op. 4",
        "Feu d'artifice. pour orchestre. Op. 4.",
        "Finlande:Poème symphonique pour orchestre",
        "Foggy Day.",
        "Fragments lyriques:pour accordéon basses mélodie",
        "Francesca da Rimini",
        "Francesca da Rimini",
        "Francesca da Rimini. Op. 25.[(Opéra;Opéras)]",
        "Francesca da Rimini. Op. 32.",
        "Frauenliebe und leben. Voix, piano. Op. 42.[(Mélodie)]",
        "Funiculi-Funiculà",
        "Funiculi-Funiculà.",
        "Georgia on My Mind",
        "Georgia on my mind.",
        "Gleichwie der Regen und Schnee vom Himmel fällt",
        "Gleichwie der Regen und Schnee vom Himmel fällt. BWV 18.",
        "Gloria",
        "Gloria:pour solistes, choeur mixte à quatre voix et orchestre",
        "Grand Duo concertant:pour violon et violoncelle",
        "Grand duo pour violoncelle et piano",
        "Grand duo:pour violoncelle et piano",
        "Grand galop chromatique",
        "Grand galop chromatique. Piano. S 219.",
        "Grande fugue op. 134:pour piano 4 mains",
        "Grosses Duet. Violoncelle, piano.",
        "Gyermekeknek. Piano. Sz 42.",
        "Halka",
        "Halka:opéra en 4 actes",
        "Halka.[(Opéra)]",
        "Hamburgisches Konzert",
        "Hamburgisches Konzert. Cor et orchestre.",
        "Hamburgisches Konzert. Cor et orchestre.",
        "Harmonies poétiques et religieuses",
        "Harmonies poétiques et religieuses. Piano. S 173.",
        "Hary Janos Suite",
        "Hary Janos Suite.",
        "Hin und zurück",
        "Hin und zurück. Op. 45a.[(Opéras)]",
        "Hongrie:Poème symphonique N° 9",
        "How High the Moon",
        "How high the moon.",
        "Huit sonates:pour trois flûtes à bec alto",
        "Humoresque:arrangement pour quatuor à cordes",
        "Hungaria",
        "Hungaria. Orchestre. S 103.",
        "Ich will den Kreutzstab gerne tragen",
        "Ich will den Kreuzstab gerne tragen. BWV 56.",
        "Ikarus. Orchestre.",
        "Il trovatore.[(Opéra)]",
        "Impromptu no 3",
        "Impromptu no 4 ou Fantaisie-impromptu",
        "Impromptu no 4 ou Fantaisie-impromptu",
        "Impromptus. Piano. No 3. CT 45. Op. 51. Sol bémol majeur.",
        "Intégrale de la musique pour consort:pour violes de gambe ou flûtes à bec",
        "Inventions et sinfonias",
        "Inventions et sinfonias",
        "Inventions. Clavier. BWV 772-773-774-775-776-777-778-779-780-781-782-783-784-785-786.",
        "Inventions. Clavier. No 4. BWV 775. Ré mineur.",
        "Israel en Egypte",
        "Israel en Egypte:Oratorio en trois parties",
        "Israel in Egypt. HWV 54.",
        "Iz evrejskoj narodnoj poezi. Op. 79.[(Chant, piano)]",
        "Iz evrejskoj narodnoj poezi. Op. 79.[(Chant, piano)]",
        "Jack in the box",
        "Jack in the box.[(Ballet;Pantomime)]",
        "Jacques dans la boîte:pour clarinette en sib et piano, arrangement.",
        "Játékok.",
        "Játékok.",
        "Játékok.",
        "Játékok.",
        "Její pastorkyna. JW I/4.",
        "Jelek, jatekok és üzenetek. Alto.",
        "Jenufa",
        "Jephta. HWV 70.",
        "Jephté",
        "Jephté:Oratorio en 3 actes pour 6 voix solistes, choeur et orchestre",
        "Jeu d'intervalles:5 duos pour cymbalum, ce cahier peut être utilisé aussi pour le clavecin ou le piano",
        "Jeu de cartes",
        "Jeu de cartes.[(Ballet en trois donnes)]",
        "Jeu de sons:pour piano à quatre mains et percussion (4 exécutants)",
        "Jeux",
        "Jeux",
        "Jeux",
        "Jeux",
        "Jeux V:pour piano, Entrées journalières, messages personnels",
        "Jeux V:pour piano, Entrées journalières, messages personnels",
        "Jeux VII:pour piano",
        "Jeux VIII:pour piano à quatre mains et pour deux pianos",
        "Joueurs de flûte",
        "Joueurs de flûte. Flûte, piano. L 32.",
        "Kát'a Kabanová. JW I/8.[(Opéra)]",
        "Katia Kabanova",
        "Katia Kabanova:opéra en trois actes",
        "Kinderszenen. Op. 15.",
        "Kinderszenen. Op. 15.",
        "Kinderszenen. Op. 15.",
        "Knâz' Igor'.[(Opéra)]",
        "Konzertstück no 2",
        "Konzertstück. Clarinette, cor de basset, orchestre. No 2. MWV Q 24. Op. 114. Ré mineur.",
        "Kuolema",
        "Kuolema",
        "L'affaire Makropoulos",
        "L'affaire Makropoulos:opéra d'après la comédie de Karel Capek",
        "L'amour des trois oranges, op. 33",
        "L'amour des trois oranges, op. 33",
        "L'amour et la vie d'une femme",
        "L'amour sorcier",
        "L'Ange de feu, op. 37",
        "L'Ascension",
        "L'Ascension.[(Poème symphonique)]",
        "L'autre côté",
        "L'autre côté.[(Opéra;Opéras)]",
        "L'enlèvement au sérail, KV 384",
        "L'Europe galante",
        "L'Exécution de Pougatchov:pour choeur mixte SSAATTTBBB avec solistes et 3 voix d'enfants SSA a cappella",
        "L'heure espagnole",
        "L'heure espagnole. O 52.[(Opéra;Opéras)]",
        "L'histoire du chevalier Constantin:pour deux guitares",
        "L'ile des morts",
        "L'impériale",
        "L'impériale. deux choeurs orchestre. Op. 26.[(Cantate;1854)]",
        "L'impériale. deux choeurs orchestre. Op. 26.[(Cantate;1854)]",
        "L'offrande musicale",
        "L'oiseau de feu",
        "L'oiseau de feu:Suite de ballet pour orchestre (version 1945)",
        "L'oiseau de feu.",
        "L'opéra de quat'sous",
        "La cathédrale engloutie. Piano. FL 125 no 10.[(Prélude)]",
        "La chatte et la belette:pour guitare",
        "La clémence de Titus",
        "La clemenza di Tito. KV 621.[(opera seria)]",
        "La collection des ensembles:6 pièces...",
        "La cour de récréation du piano:douze pièces pour les jeunes",
        "La création",
        "La descente d'Orphée aux Enfers",
        "La descente d'Orphée aux Enfers. H 488.[(Opéra;Opéras)]",
        "La fin:musique pour piano avec orchestre",
        "La flûte enchantée",
        "La Flûte enchantée:opéra allemand en deux actes",
        "La Gioconda",
        "La Gioconda.[(Opéra)]",
        "La musique pour les feux d'artifice royaux:pour orchestre",
        "La nouvelle Babylone",
        "La Nouvelle Babylone:Musique pour le film muet de G. Kozintsev",
        "La petite renarde rusée",
        "La petite renarde rusée:opéra en 3 actes",
        "La première nuit de Walpurgis",
        "La première nuit de Walpurgis (Les Sorcières):pour solistes (alto, ténor, et baryton), choeur (mixte) et orchestre",
        "La Traviata",
        "La Traviata.[(Opera;Operas)]",
        "La vida breve.[(Opéra)]",
        "La vie brève",
        "Lady Macbeth de Mzensk",
        "Lady Macbeth du district de Mzensk:opéra en quatre actes et 9 tableaux. Version de 1932 (première édition). Réduction piano-chant",
        "Lakmé",
        "Lakmé.[(Opéra;Opéras)]",
        "Le barbier de Seville:arrangé pour flöte, violon, alto et violoncelle",
        "Le beau Danube bleu",
        "Le beau Danube bleu:valse pour orchestre Op.314",
        "Le comte Ory",
        "Le comte Ory",
        "Le comte Ory.[(Opéra)]",
        "Le comte Ory.[(Opéra)]",
        "Le corridor éternel:pour choeur mixte a cappella ou choeur mixte et instruments",
        "Le crocodile à touches à quatre mains:pièces faciles pour piano à quatre mains",
        "Le Fidèle Maître de Musique:Une sélection de pièces pour flûte (flûte à bec ou autres instruments solistes) et basse continue",
        "Le lac enchanté",
        "Le marteau sans maître",
        "Le marteau sans maître.",
        "Le nozze di Figaro. KV 492.[(Opéra)]",
        "Le nozze di Figaro. KV 492.[(Opéra)]",
        "Le nozze di Figaro. KV 492.[(Opéra)]",
        "Le Parnasse, ou l'Apothéose de Corelli",
        "Le Parnasse.",
        "Le Pèlerinage de la rose, op. 112",
        "Le pélerinage de la Rose:conte de fées d'après un poème de Moritz Horn pour solistes, choeur et orchestre",
        "Le petit nègre",
        "Le prince Igor",
        "Le rossignol",
        "Le rossignol.[(Opéra)]",
        "Le sacre du printemps",
        "Le Sacre du printemps.",
        "Le Siège de Corinthe",
        "Le siège de Corinthe.[(Opéra)]",
        "Le songe d'une nuit d'été",
        "Le temps l'horloge",
        "Le temps l'horloge. cinq épisodes pour soprano et orchestre.",
        "Le tricorne",
        "Le tricorne",
        "Le trouvère",
        "Le voyage d'hiver",
        "Le voyage d'hiver",
        "Le voyage d'hiver",
        "Le voyage d'hiver:version pour voix élevée",
        "Le voyage d'hiver:version pour voix grave",
        "Le voyage d'hiver:version pour voix moyenne",
        "Le voyage de Monsieur Broucek (cafard en tchèque) vers la lune:opéra en deux actes et un epilogue, acte 1",
        "Le voyage de Monsieur Broucek (cafard en tchèque) vers la lune:opéra en deux actes et un epilogue, acte 2 et epilogue",
        "Légendes. Piano. S 175.",
        "Légendes. Piano. S 175.",
        "Les amours du poète, op. 48",
        "Les classiques de la guitare:études et pièces de concert des 18ème et 19ème siècles. Premier volume : niveau intermédiaire",
        "Les contes d'Hoffmann",
        "Les contes d'Hoffmann.[(Opéra;Opéras)]",
        "Les créatures de Prométhée",
        "Les cyprès",
        "Les dix-neuf madrigaux italiens:dix-huit à cinq voix et un double choeur à huit voix",
        "Les Feuilles mortes",
        "Les Feuilles mortes.",
        "Les maitres de la musique de chambre vocale:Duos, un trio et un quatuor avec accompagnement de piano et textes originaux",
        "Les mamelles de Tirésias",
        "Les mamelles de Tirésias. FP 125.[(Opéra;Opéras)]",
        "Les noces de Figaro, KV 492",
        "Les noces de Figaro, KV 492",
        "Les noces de Figaro, KV 492",
        "Les nuits d'été",
        "Les nuits d'été. Voix, orchestre. H 81B.",
        "Les Plus jolies études:pour flûte",
        "Les première études:Cent petites pièces techniques pour débutants",
        "Les saisons",
        "Les Saisons:Chants sur des poèmes de Scardanelli (Hölderlin), pour choeur mixte à capella",
        "Les sept dernières paroles du Christ",
        "Les vêpres siciliennes",
        "Les vêpres siciliennes.[(Opéra)]",
        "Lieder album für die Jugend. Voix, piano. Op. 79.",
        "Liederkreis, op. 39",
        "Liederkreis. Voix, piano. Op.39.",
        "Lûbov k trem apel'sinam. Op. 33.[(Opéra)]",
        "Lûbov k trem apel'sinam. Op. 33.[(Opéra)]",
        "Lyriques castillanes:pour soprano, fllûte à bec (flûte), cornet de bois (à bouquin?, hautbois) et vihuela (guitare)",
        "Mack The Knife (Moritat)",
        "Mack the knife.",
        "Magnificat",
        "Magnificat:pour solistes, 2 choeurs mixtes à quatre voix et 2 orchestres. Réduction pour piano.",
        "Maple Leaf Rag",
        "Maple Leaf Rag",
        "Maple Leaf Rag. Piano. La bémol majeur.[(Ragtime;1899)]",
        "Maple Leaf Rag. Piano. La bémol majeur.[(Ragtime;1899)]",
        "Marche solennelle pour les célébrations de Goethe",
        "Marimba et percussion:quatre pièces pour trois percussionnistes",
        "Mazurka brillante",
        "Mazurka brillante. Piano. S 221.",
        "Mazurka op. 59 n°2:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Mazurka op. 59 n°2:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Mazurka op. 59 n°2:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Mazurka op. 59 n°2:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Mazurkas opus 33:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Mazurkas. Piano. no 37. CT 87. Op. 59 no 2.",
        "Mazurkas. Piano. no 5. CT 56. Op. 7 no 1. Si bémol majeur.",
        "Mazurkas. Piano. no 8. CT 59. Op.7 no 4. La bémol majeur.",
        "Meeresstille und glückliche Fahrt. MWV P 5. Op. 27. Ré majeur.",
        "Mélodies anciennes françaises:pour flûte à bec sorpano",
        "Mélodies:pour chant et piano (voix grave)",
        "Mélodies:pour voix et piano (voix grave)",
        "mémoire:pour choeur mixte à huit voix",
        "Menuets, valses, danses paysannes (tyroliennes), écossaises:arrangées pour flûte (ou violon) et guitare d'après les urtext pour le piano.",
        "Méphisto-polka",
        "Mephisto-Polka. Piano. S 217.",
        "Méphisto-valse no 1",
        "Méphisto-valse no 2",
        "Méphisto-valse no 3",
        "Méphisto-valse no 4",
        "Mephisto-Walzer. Piano. N° 2. S 515.",
        "Mephisto-Walzer. Piano. N° 3. S 216.",
        "Mer calme et heureux voyage",
        "Messa da requiem.",
        "Messe brève en Fa Majeur:pour choeur SATB, 2 sopranos solos et orchestre : réduction pour piano",
        "Messe de Requiem:pour l'anniversaire de la mort de Manzoni, 22 mai 1874 ; réduction pour voix et piano basée sur l'édition critique de la partition d'orchestre",
        "Méthode de piano:musique baroque et musique hongroise d'aujourd'hui",
        "Mini musique:pour deux percussionnistes",
        "Modus vivendi:pour flûte et guitare",
        "Monument ; Selbstportrait ; Bewegung",
        "Monument, Selbsportrait, Bewegung, Pianos",
        "Moonlight in Vermont",
        "Morceau de concert no. 2 en ré mineur:pour claritette, cor de basset (ou 2 clarinettes) et piano, orchestré par Carl Baermann",
        "Morceau N°1, sans titre (Musique sans nom):pour flûte et guitare",
        "Motet allemand",
        "Motet allemand:pour quatre voix solistes et choeur mixte à 16 parties",
        "Motet pour une cérémonie funèbre 'Oh Jésus, lumière de ma vie' BWV 118:pour choeur et orchestre, réduction avec piano",
        "Mouvements de danse à quatre voix:Villanelles et mauresques choisies, pour quatuor de flûtes à bec ou autres instruments mélodiques",
        "Music for the Royal Fireworks",
        "Music for the Royal Fireworks. HWV 351.",
        "Musikalisches Opfer. BWV 1079.",
        "Musique de chambre:pour flûte à bec (flûte à bec alto et flûte à bec basse) et accodéon",
        "Musique de table",
        "Musique de table",
        "Musique pour cuivres VII:Entrées de Kromer, revisées et avec une rajoutée de timbales et de 3 trompette",
        "Musique pour guitare des 16ème-18ème siècles:d'après des tablatures pour colascione, mandore et angelica",
        "Musique pour percussions à clavier:14 duos et soli pour percussions à clavier (vibraphone, marimba, vibraphone, metallophone)",
        "Musique pour piano:une selection de célèbres pièces pour piano de Manuel de Falla, comprenant pièces originales et arrangements.",
        "Musique pour piano:une selection de célèbres pièces pour piano de Manuel de Falla, comprenant pièces originales et arrangements.",
        "My Funny Valentine",
        "My Funny Valentine",
        "My Funny Valentine.",
        "My Funny Valentine.",
        "Myla et l'arbre-bateau. Récitant, choeur d'enfant et ensemble instrumental ou piano.",
        "Myrthen, op. 25",
        "Myrthen. Voix, piano. Op. 25.",
        "Nabucco",
        "Nabucco.[(Opéra)]",
        "Neuf airs allemands",
        "Neuf airs allemands HWV 202-210:pour soprano, un instrument soliste et basse continue",
        "Neuf danses du 16ème siècle:pour flûte à bec et guitare",
        "Neun deutsche Arien. HWV 202-203-204-205-206-207-208-209-210.[(Aria)]",
        "Nocturne du 2e quatuor à cordes:arrangement pour clarinette et piano",
        "Nocturne opus 27 n°2:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Nocturne:pour petit orchestre avec violoncelle solo",
        "Nocturnes. Piano. Op. 27 no 2. Ré bémol majeur.",
        "Noëls [pour orgue] op. 145/3:arrangement pour pour violon (flûte), violoncelle et orgue (piano)",
        "Notturno",
        "Notturno.",
        "Nouvelle école de harpe Vol.III:Introduction au jeu en orchestre : études d'orchestre I",
        "Nouvelle méthode de harpe:histoire et méthode",
        "Novyj Vavilon. Op. 18.[(Musique de film)]",
        "O Jesu Christ, mein Lebens Licht",
        "O Jesu Christ, mein Lebens Licht. BWV 118.",
        "Octuor à cordes",
        "Octuor opus 20:pour quatre violon, deux altos et deux violoncelles",
        "Octuors. Cordes. MWV R 20. Op. 20. Mi bémol majeur.",
        "Ode à la mort de Monsieur Henry Purcell:pour deux contreténors (contraltos), deux flûtes à bec soprano et clavecin (ou piano) avec violoncelle ad lib.",
        "Ode à la Paix:Concerto pour orgue seul",
        "Ode an eine Aolsharfe",
        "Ode an eine Aolsharfe. Guitare, ensemble instrumental.",
        "Ode sur la mort de Mr Henry Purcell",
        "Oeuvres choisies:pour piano",
        "Oeuvres cycliques choisies, vol II:pour piano solo",
        "Oeuvres de l'école hollandaise:pour 4 instruments",
        "Oeuvres pour clavier:premier recueil de 1720 : les huit Grandes suites",
        "Ognenny angel. Op. 37.[(Opéra)]",
        "Ol' Man River",
        "Ol' Man River.",
        "Oratorio de Noël, op. 12",
        "Oratorio de Noël. Op. 12.[(Oratorios)]",
        "Ostrov mertvyh. Op. 19.",
        "Ouevres pour le piano, Volume III:Oeuvres de 1996 à 2003",
        "Ouverture dans le style italien en do majeur, D 591",
        "Ouverture dans le style italien en Do Majeur:pour orchestre",
        "Ouverture dans le style italien en ré majeur, D 590",
        "Ouverture dans le style italien en Ré Majeur:pour orchestre",
        "Ouverture et conclusion en Mi mineur, de la 'Musique de table I':pour deux flûtes, cordes et basse continue",
        "Ouvertures. MWV P 2. Op. 101. Do majeur.",
        "Ouvertures. Orchestre. D 590. Ré majeur.",
        "Ouvertures. Orchestre. D 591. Op. 170. Do majeur.",
        "Parade militaire des petits gnomes:pour quatuor à cordes",
        "Paraphrase du Cristus:Cantate spitiruelle pour soprano, alto et cordes ; version pour voix et piano",
        "Partita:pour flûte, violon et basse continue",
        "Partita:pour orchestre à cordes",
        "Passacaille et fugue:pour trio à cordes",
        "Passion selon St. Jean:Histoire du Martyr et de la mort de notre seigneur Jesus Christ d'après Saint Jean l'évangeliste pour quatre solistes et choeur à quatre voix sans accompagnement",
        "Paysages sonores d'hiver:Sept pièces originales pour quatuor à cordes de niveau moyen",
        "Peer Gynt, musique de scène",
        "Peer Gynt. Op. 23.[(Musique de scène)]",
        "Percussion classique:oeuvres de compositeurs anciens arrangées pour marimba et vibraphone",
        "Persée",
        "Persée. LWV 160.[(Opéra;Opéras)]",
        "Petit trio avec piano:pour violon, violoncelle et piano",
        "Petites pièces pour clavier de Bach et de Haendel:arrangées pour l'accordéon",
        "Phaéton",
        "Phaéton",
        "Phaéton. LWV 61.",
        "Phaéton. LWV 61.",
        "pièces anglaises anciennes faciles:pour flûte à bec (ou autre instrument) et guitare ou 2 guitares",
        "Pièces célèbres tirées du Petit Cahier de Johann Sebastian Bach pour Anna Magdalena Bach, et de Leopold Mozart pour Wolfgang Amadeus Mozart:pour le violoncelliste débutant (en différentes distributions instrumentales) dans la première position",
        "Pièces choisies:transcription pour 1 et 2 guitares",
        "Pièces en solo pour flûte à bec soprano:chansons et danses",
        "Più non si trovano, KV 549",
        "Più non si trovano. K 549.[(Canzonetta)]",
        "Po zarostlém chodnicku. Piano. JW VIII/17.",
        "Poème élégiaque",
        "Poème élégiaque. Violon, piano. Op. 12.",
        "Pogrebal'naya Pesnya. Orchestre. Op. 5.",
        "Pohadka",
        "Pohadka. Violoncelle, piano.",
        "Polo. Voix, piano.",
        "Polonaise no 7 ou Polonaise-fantaisie",
        "Polonaises. Piano. No 7. CT 156. Op. 61.",
        "Pops classiques:pour violon et violoncelle",
        "Pour les enfants, Sz 42",
        "Pour les jeunes flûtistes:10 [Dix] pièces contemporaines pour flûte solo ou ensemble de flûtes",
        "Prejs,Alexander .",
        "Prélude basé sur J. S. Bach 'Weinen, Klagen, Sorgen, Zagen', et Variations sur un motiv de Bach.:pour piano",
        "Prélude et scherzo",
        "Prélude et Scherzo:pour octuor à cordes",
        "Prélude et scherzo. Octuor à cordes. Op. 11.",
        "Prélude sur des chorals pour orgue:transcription pour piano",
        "Prélude, quatre variations et finale:pour violoncelle et orchestre, édition avec piano",
        "Préludes (Livre 1)",
        "Prelyudiya. Piano. Op. 3 no 2. Do dièse mineur.",
        "Première sonate en Ré Majeur:pour violon, viole de gambe (ou 2e. violon) et basse continue",
        "Pression",
        "Pression:pour un violoncelliste",
        "Pression.",
        "Príhody lisky Bystrousky. JW I/9.[(Opéra)]",
        "Prometej. Op. 60. Poéme du Feu.",
        "Prométhée",
        "Prométhée op. 43:Ouverture pour le ballet 'Les créatures de Prométhée'",
        "Prométhée:Le poème du feu",
        "Propium:pour la fête de la Messe de la Trinité, pour 2 trompettes, timbales, soprano, choeur mixte à quatre voix, choeur paroissial et orgue",
        "Proserpine",
        "Proserpine. LWV 58.[(Opéra)]",
        "Quartettsatz (mouvement de quatuor)",
        "Quatre danses norvégiennes",
        "Quatre danses:pour trois percussionnistes",
        "Quatre duos:pour violon et alto",
        "Quatre illustratios:pour piano seul",
        "Quatre impromptus, D 899",
        "Quatre mazurkas Op.33",
        "Quatre mouvements:pour quatuor à cordes",
        "Quatre pièces:pour trois instruments ATB (Alto, Ténor, Basse)",
        "Quatre poèmes symphoniques pour grand orchestre d'après Arnold Böcklin",
        "Quatre suites:pour flûte à bec (violon, flûte traversière ou hautbois) et basse continue",
        "Quatre tangos, volume I:pour trio avec piano (Piano, Violon, Violoncelle)",
        "Quatre tangos, volume II:pour trio avec piano (Piano, Violon, Violoncelle)",
        "Quatrième sonate en Do Majeur:pour violon, viole de gambe (ou 2e. violon) et basse continue",
        "Quatuor 'Petite musique', op. 29b:pour cor de basset, violon, alto et violoncelle",
        "Quatuor à cordes",
        "Quatuor à cordes en Lab Majeur, op.105:pour 2 violons, alto et violoncelle",
        "Quatuor à cordes no 1",
        "Quatuor à cordes no 12 'Américain'",
        "Quatuor à cordes no 14",
        "Quatuor à cordes no 2 en fa majeur, op. 92",
        "Quatuor à cordes no 8 en si bémol majeur, D 112",
        "Quatuor à cordes No.2, Op.92, sur des thèmes kabardiniens:pour 2 violons, alto et violoncelle",
        "Quatuor à cordes Opus 64 N°3:pour 2 violons, alto et violoncelle",
        "Quatuor avec piano et cordes en Do mineur:pour violon, alto, violoncelle et piano",
        "Quatuor en Do mineur D 703. Opus posthume:pour 2 violons, alto et violoncelle",
        "Quatuor en Do mineur:pour hautbois (ou violon), violon, alto et basse continue",
        "Quatuor en fa mineur op.13:pour violon, alto, violoncelle et piano",
        "Quatuor en La majeur, op.26:pour piano, violon, alto et violoncelle",
        "Quatuor en La mineur Op. 133:pour violon, alto, violoncelle et piano",
        "Quatuor en Mi mineur:pour 2 violons, alto et violoncelle",
        "Quatuor en Ré Majeur D 353, Op. 125 No.2:pour 2 violons, alto et violoncelle",
        "Quatuor en Ré mineur:pour flûte, clarinette (Sib), cor (Fa) et basson",
        "Quatuor en Sib Majeur D 112, Op. 168:pour 2 violons, alto et violoncelle",
        "Quatuor en Sol Majeur:pour flûte, 2 violes de gambe et basse continue",
        "Quatuor en Sol mineur D 173:pour 2 violons, alto et violoncelle",
        "Quatuor en Sol mineur Op.27:pour 2 violons, alto et violoncelle",
        "Quatuor Fa majeur, Op. 11, N°3:pour flûte, clarinette (Sib), cor (Fa) et basson",
        "Quatuor Fa majeur:pour flûte, clarinette (Sib), cor (Fa) et basson",
        "Quatuor N°1, op. 79, d'après le KV 317d (378):pour clarinette, violon, alto et violoncelle",
        "Quatuor N°6, l'Offrande musicale:pour trompette aiguë, trompette en Sib ou en Ut, cor et trombone basse",
        "Quatuor op.8 N°4 en Mib Majeur:pour clarinette (ou hautbois), violon, alto et violoncelle",
        "Quatuor op.8 N°4 en Mib Majeur:pour clarinette (ou hautbois), violon, alto et violoncelle",
        "Quatuor pour clarinette, violon, violoncelle et piano",
        "Quatuor pour flûte et cordes no 1 en ré majeur, KV 285",
        "Quatuor pour instruments à vent, en Mib majeur:pour hautbois, clarinette (Sib), cor (Mib) et basson",
        "Quatuor pour piano et cordes no 2 en la majeur, op. 26",
        "Quatuor:pour clarinette et trio à cordes",
        "Quatuor:pour clarinette, violon, violoncelle et piano",
        "Quatuor. Clarinette, violon, violoncelle, piano.",
        "Quatuor. Cordes. Mi mineur.",
        "Quatuor. Cordes. N° 1. Op. 27. Sol mineur.",
        "Quatuor. Cordes. N° 2. Ré majeur.",
        "Quatuor. Cordes. N°8. D.112. op. 168. Si bémol majeur.",
        "Quatuor. Cordes. no 12. B 179. Op. 96. Fa majeur. Américain.",
        "Quatuor. Cordes. No 14. B 193. Op. 105. La bémol majeur.",
        "Quatuor. Cordes. No 2. Op. 92. Fa majeur.",
        "Quatuor. Flûte, violon, alto, violoncelle. K 285. Ré majeur.",
        "Quatuor. Piano, cordes. No 2. Op. 26. La majeur.",
        "Quels accents bélliqueux [écoutes-tu, mon coeur?]:Cantate pour soprano, trompette obligée et base continue",
        "Quintette à cordes en do majeur, D 956",
        "Quintette en Si mineur op. 115:pour clarinette, 2 violons, alto et violoncelle",
        "Quintette en Si mineur:pour deux flûtes, deux flûtes à bec et basse continue",
        "Quintette Opus 57:pour piano, 2 violons, alto et violoncelle",
        "Quintette pour clarinette et cordes en si mineur, op. 115",
        "Quintette pour deux violons, alto, violoncelle et piano en mi majeur",
        "Quintette pour piano et cordes",
        "Quintette:pour 2 violons, alto, violoncelle et piano",
        "Quintettes. 2 violons, alto, violoncelle, piano. Op. 15. Mi majeur.",
        "Quintettes. Clarinette. Cordes. Op. 115. Si mineur.",
        "Quintettes. Cordes. D.956. Op. 163. Do majeur.",
        "Quintettes. Piano, cordes. Op. 57. Sol mineur.",
        "Qutre bagatelles:pour alto (ou clarinette ou saxophone alto)",
        "Récitatifs et fugues:pour piano",
        "Réjouis-toi!:sonate pour violon et violoncelle",
        "Renard, histoire burlesque jouée et chantée",
        "Renard.[(Ballet, pantomime)]",
        "Requiem",
        "Requiem",
        "Requiem en Réb Majeur:pour soli, choeur et orchestre : réduction pour piano par le compositeur",
        "Requiem, op. 148",
        "Requiem.",
        "Requiem. Op. 148.",
        "Rhapsodie pour alto, choeur d'hommes et orchestre, op. 53",
        "Rhapsodie pour alto, choeur d'hommes et orchestre. Op. 53.",
        "Rhapsodie:pour contralto, choeur d'hommes et orchestre d'après 'le voyage d'hiver aux montagnes du Harz', réduction pour piano par le compositeur",
        "Rigoletto",
        "Rigoletto",
        "Rigoletto.[(Opéra;Opéras)]",
        "Rigoletto.[(Opéra;Opéras)]",
        "Ritter vom Steckenpferd. No 9. Op. 15. Do majeur.",
        "Romance tirée de 'La petite musique de nuit' ; 'La ci darem la mano' (Nous nous donnerons la main) tiré de Don Giovanni:arrangés pour ensemble à vents",
        "Romance:pour piano en Réb Majeur",
        "Salve Regina",
        "Salve Regina:Concert Sacré pour soprano, cordes et orgue",
        "Salve Regina:pour contralto et deux orchestres : réduction pour piano",
        "Salve Regina. HWV 241.[(Motet)]",
        "Samba-Salsa-Son:9 arrangements pour instrumentation variable",
        "Scènes d'enfants, op. 15",
        "Scènes d'enfants, op. 15",
        "Scènes d'enfants, op. 15",
        "Scheherazade Op.35:thèmes connus pour deux violons et piano",
        "Scherzi musicaux, Suite I:pour viole de gambe et basse continue",
        "Scherzi musicaux, Suite II:pour viole de gambe et basse continue",
        "Scherzi musicaux, Suites 10 et 11:pour viole de gambe et basse continue",
        "Scherzi musicaux, Suites 12 à 14:pour viole de gambe et basse continue",
        "Scherzi musicaux, Suites 3 à 5:pour viole de gambe et basse continue",
        "Scherzi musicaux, Suites 6 et 7:pour viole de gambe et basse continue",
        "Scherzi musicaux, Suites 8 et 9:pour viole de gambe et basse continue",
        "Schicksalslied. Op. 54.",
        "Sechs Deutsche. piano. D 820.",
        "Sechs Gesänge aus dem Arabischen.",
        "Sechs kleine Klavierstücke. Piano. op. 19.",
        "Sechzehn Deutsche und zwei Ecossaisen. Piano. D 783. Op. 33.",
        "Seherazada. Op. 35.[(Suite)]",
        "Seize allemandes et deux écossaises, D 783",
        "Selkuncik. Op. 71.[(Ballet)]",
        "Sept chansons populaires espagnoles",
        "Sept chansons populaires espagnoles",
        "Sept chants sur des textes de Walter Scott, op. 52",
        "Sept chorales de Bach:transcription pour piano à 4 mains",
        "Sept lieder. Op. 52.",
        "Sept pièces instrumentales à 3 voix:soprano, ténor et basse",
        "Sept variations pour violoncelle et piano sur le thème 'Bei Männern, welche Liebe fühlen' de La Flûte enchantée de Mozart",
        "Sérénade N°1, Opus 11, en Ré Majeur:pour grand orchestre",
        "Sérénade no 1 en ré majeur, op. 11",
        "Sérénade no 13 en sol majeur, KV 525 'Petite musique de nuit'",
        "Sérénade no 13 en sol majeur, KV 525 'Petite musique de nuit'",
        "Sérénade pour orchestre à cordes",
        "Sérénade:trio pour cor de basset, alto et violoncelle",
        "Sérénade. Orchestre à cordes. Op. 2.",
        "Serenades 1:pour trois instruments mélodiques ou pour un instrument mélodique et piano",
        "Sérénades 2:pour trois instruments mélodiques ou un instrument mélodique et piano",
        "Sérénades 3:pour trois instruments mélodiques ou un instrument mélodique et piano",
        "Sérénades, N°.4:pour trois instruments mélodiques ou un instrument mélodique et piano",
        "Serenades:pour 3 instruments mélodiques ou 1 instrument et piano",
        "Serenades:pour 3 instruments mélodiques ou 1 instrument et piano",
        "Serenades:pour 3 instruments mélodiques ou 1 instrument et piano",
        "Serenades:pour 3 instruments mélodiques ou 1 instrument et piano",
        "Sérénades. Orchestre. no 1. Op. 11. Ré majeur.",
        "Shéhérazade",
        "Siete canciones populares españolas. Voix, piano.",
        "Signes, jeux et messages",
        "Signes, Jeux et Messages:pour Alto",
        "Six Canzonettes d'après KV 346, 436-439 et 549:pour 3 flûtes",
        "Six chants de l'arabe",
        "Six chants des arabes:pour ténor et piano",
        "Six concerts en trio:pour deux instruments mélodiques (flûtes, violons, hautbois etc.) et basse continue",
        "Six danses allemandes, D 820",
        "Six danses hongroises:pour flûte (violon), violoncelle et piano",
        "Six Duos op. 19:pour violon et alto",
        "Six duos op.21:pour clarinette et basson ou violoncelle",
        "Six duos:pour violon et violoncelle",
        "Six Fragment de Hölderlin:pour voix et piano",
        "Six petites pièces pour piano, op. 19",
        "Six petites pièces pour quatre flûtes:La Locomotive ; les Chats ; le Coucou ; Berceuse ; le Rêveur ; Valse",
        "Six pièces extraites de 'Water Music': pour flûte à bec soprano et piano",
        "Six sonates d'après BWV 525-530:pour flûte et clavecin obligé, vol. III, Sonates 5 et 6",
        "Six sonates faciles:pour viole de gambe et basse continue ou pour autres instruments",
        "Six sonates faciles:pour viole de gambe et basse continue ou pour autres instruments",
        "Six sonates Op.2. pour 2 violes de gambe.:Sonates I à III",
        "Six sonates Op.2. pour 2 violes de gambe.:Sonates IV à VI",
        "Six sonates:pour flûte et clavecin",
        "Six suites (en 2 volumes):pour deux flûtes à bec alto",
        "Six trios:pour flûte, violon ou 2 violons et violoncelle",
        "Sixième sonate, en Fa Majeur:pour violino piccolo (ou violon), viole de gambe (ou 2e. violon) et basse continue",
        "Sixième sonate, tirée de La Cetra, Op.10 [2 versions : grave et aigue]:pour consort de 4 violes de gambe et basse continue",
        "Slovanské tance. Orchestre. n°s 9 à 16. B 147.",
        "Smutna Opowiesc (Preludia do Wieczonisci).",
        "Solo en Ré Majeur:pour viole de gambe et basse continue",
        "Solo en Sib Majeur:pour viole de gambe et basse continue",
        "Solo pour viole de gambe:Sonate en Ré Majeur pour Viole de Gambe et Basse continue",
        "Sonate '1er octobre 1905', en mi bémol mineur",
        "Sonate à trois:pour deux flûtes à bec alto (ou flûtes traversières ou hautbois ou violons) et basse continue.",
        "Sonate berlinoise:pour ensemble à trois voix de flûtes à bec à l'octave",
        "Sonate en Do Majeur:pour 3 violes de gambe et basse continue",
        "Sonate en Do Majeur:pour flûte à bec alto (ou flûte traversière ou hautbois), deux violons et basse continue",
        "Sonate en Do Majeur:pour piano et violoncelle",
        "Sonate en Do Majeur:pour viole de gambe et basse continue",
        "Sonate en Do mineur:pour flûte à bec alto et clavecin obligé",
        "Sonate en do mineur:pour flûte, hautbois (ou violon) et basse continue",
        "Sonate en Fa Majeur:pour flûte à bec alto (ou flûte traversière ou hautbois), deux violons et basse continue",
        "Sonate en Fa Majeur:pour viole de gambe ou alto et clavecin obligé.",
        "Sonate en La Majeur:pour clavecin obligé (ou pianoforte) et viole de gambe",
        "Sonate en La mineur ; Suite en Ré mineur [Attribuées]:pour 2 violes de gambe et basse continue",
        "Sonate en la mineur 'l'infidèle':pour luth",
        "Sonate en La mineur dite 'Arpeggione':arrangée pour flûte et piano",
        "Sonate en La mineur, op. 34/6:pour 3 instruments mélodiques (flûtes, violons, hautbois) ou orchestre à cordes et basse continue",
        "Sonate en la mineur:pour flûte à bec (ou flûte, violon ou hautbois) et guitare",
        "Sonate en la mineur:pour violoncelle (basson) et guitare",
        "Sonate en Ré Majeur op. 37 /3:pour flûte (ou hautbois ou violon), viole de gambe (ou basson ou violoncelle) et basse continue",
        "Sonate en Ré Majeur, Ecole berlinoise (Bibliothèque Amalia):pour basse de viole et clavecin obligé (piano)",
        "Sonate en Ré Majeur:pour alto et basse continue ou pour alto et violoncelle",
        "Sonate en Ré Majeur:pour viole de gambe et clavecin obligé",
        "Sonate en Ré mineur pour viole de gambe et basse continue:extraite du cahier de viole de gambe de Lübeck, auteur anonyme",
        "Sonate en ré mineur:pour flûte à bec alto, 2 violons et basse continue",
        "Sonate en Si mineur:pour flûte traversiére, violon, violoncelle et basse continue",
        "Sonate en Sib Majeur:pour basson et violoncelle",
        "Sonate en Sol mineur, TWV 42:g7:pour flûte, viole (de gambe) et basse continue",
        "Sonate en sol mineur:pour flûte à bec alto et basse chiffrée (piano, clavecin) avec violoncelle ad lib.",
        "Sonate en Sol mineur:pour viole de gambe et clavecin",
        "Sonate en Sol mineur:pour viole de gambe et clavecin",
        "Sonate en trio en Mb Majeur:pour hautbois, hautbois de chasse (ou violon) et basse continue",
        "Sonate en Trio en Mi mineur:pour deux flûtes et basse continue",
        "Sonate en trio en Mib majeur BWV 525:pour hautbois, hautbois de chasse (ou violon) et basse continue",
        "Sonate en trio en Mib Majeur:pour flûte, violon et basse contunue",
        "Sonate en trio en Sol majeur:pour flûte, violon (ou 2 flûtes) et basse continue attribuée à J.S. Bach",
        "Sonate en trio N°28, en Do mineur:pour deux hautbois (ou flûtes ou violons) et basse continue",
        "Sonate en trio opus 2 /5, HWV 390a:pour deux violons et basse continue",
        "Sonate en trio pour orgue no 1 en mi bémol majeur, BWV 525",
        "Sonate en trio pour orgue no 2 en do mineur BWV 526",
        "Sonate en trio pour orgue no 3 en ré mineur BWV 527",
        "Sonate en trio pour orgue no 4 en mi mineur, BWV 528",
        "Sonate en trio pour orgue no 5 en do majeur, BWV 529",
        "Sonate en trio pour orgue no 6 en sol majeur, BWV 530",
        "Sonate méthodique en Sol majeur d'après l'Op. XIII /3 en Mi mineur:pour flûte à bec alto et basse continue",
        "Sonate N°2:pour piano",
        "Sonate no 16",
        "Sonate no 3 pour violon et piano",
        "Sonate No.1, opus 12:pour piano",
        "Sonate opus 6:pour violon et piano",
        "Sonate pour alto et piano",
        "Sonate pour arpeggione et piano en la mineur, D 821",
        "Sonate pour basson et violoncelle, KV 196c",
        "Sonate pour flûte et basse continue en la mineur HWV 362",
        "Sonate pour piano en si mineur, opus 58:Edition fac-similée d'après les exemplaires du Musée Fréderic Chopin de Varsovie",
        "Sonate pour piano no 1",
        "Sonate pour piano no 16 en do majeur, KV 545 'Facile'",
        "Sonate pour piano no 2",
        "Sonate pour piano no 3",
        "Sonate pour piano no 5",
        "Sonate pour piano no 5 en sol majeur, KV 189h",
        "Sonate pour piano no 6 en ré majeur, KV 205b 'Dürnitz'",
        "Sonate pour piano no 7 en si bémol majeur, op. 83",
        "Sonate pour piano no 8 'Pathétique'",
        "Sonate pour violon et piano en si bémol majeur, KV 317d",
        "Sonate pour violon et piano en sol majeur, KV 293a",
        "Sonate pour violoncelle et piano no 1 en fa majeur, opus 5 no 1",
        "Sonate pour violoncelle et piano no 2",
        "Sonate pour violoncelle et piano no 3 en la majeur, opus 69",
        "Sonate pour violoncelle et piano no 4",
        "Sonate pour violoncelle et piano no 5",
        "Sonate:en Ré Majeur pour Viole de Gambe, Violone et Basse continue",
        "Sonate:en Ré Majeur pour Viole de Gambe, Violone et Basse continue",
        "Sonate:pour alto et contrebasse",
        "Sonate:pour alto et piano",
        "Sonate:pour trois violons et basse continue",
        "Sonate:pour violon et piano",
        "Sonate. Violon, piano. No 2. BV 244. op. 36a. Mi mineur.",
        "Sonates classiques faciles:flûte",
        "Sonates de chambre op.2:pour 2 violons et basse continue (théorbe ou violone)",
        "Sonates en trois parties [12 sonates]:Sonates 1 à 6",
        "Sonates en trois parties [12 sonates]:Sonates 7 à 12",
        "Sonates et danses, tirées de l'opus 22:pour 1 à 3 violons, alto, violoncelle et basse continue",
        "Sonates et danses, tirées de l'opus 22:pour 2 violons (ou flûtes à bec), alto ou viole, et basse continue",
        "Sonates op.1 à trois, 1er volume:pour 2 violons, violoncelle et orgue",
        "Sonates op.1 à trois, 2e volume:pour 2 violons, violoncelle et orgue",
        "Sonates. Arpeggione, piano. D 821. La mineur.",
        "Sonates. Basson, violoncelle. K 196c. Si bémol majeur.",
        "Sonates. Clavier. no 16. Hob XVI 46. La bémol majeur.",
        "Sonates. Flûte, basse continue. HWV 362. Op. 1 no 4. La mineur.",
        "Sonates. Orgue. no 1. BWV 525. Mi bémol majeur.",
        "Sonates. Orgue. no 2. BWV 526. Do mineur.",
        "Sonates. Orgue. no 3. BWV 527. Ré mineur.",
        "Sonates. Orgue. no 4. BWV 528. Mi mineur.",
        "Sonates. Orgue. no 6. BWV 530. Sol majeur.",
        "Sonates. Orgue. no 6. BWV 530. Sol majeur.",
        "Sonates. Piano, alto. Op. 147.",
        "Sonates. Piano, violon. K 293a. Sol majeur. Palatine.",
        "Sonates. Piano, violon. KV 317d. Si bémol majeur.",
        "Sonates. Piano. No 1. Op. 12.",
        "Sonates. Piano. No 16. K 545. Do majeur. Facile.",
        "Sonates. Piano. No 2. Op. 61. Si mineur.",
        "Sonates. Piano. No 3. CT 203. Op. 58. Si mineur.",
        "Sonates. Piano. No 5. K 189h. Sol majeur.",
        "Sonates. Piano. No 5. Op. 10 no 1. Do mineur.",
        "Sonates. Piano. No 6. K 205b. Op. 7 no 2. Ré majeur. Dürnitz.",
        "Sonates. Piano. No 7. Op. 83. Si bémol majeur.",
        "Sonates. Piano. No 8. Op. 13. Do mineur. Pathétique.",
        "Sonates. Violon, piano. No 3. FL 148. Sol mineur.",
        "Sonates. Violoncelle, piano. No 1. Op. 5 no 1. Fa majeur.",
        "Sonates. Violoncelle, piano. No 3. Op. 69. La majeur.",
        "Sonates. Violoncelle, piano. No 4. Op. 102 no 1. Do majeur.",
        "Sonates. Violoncelle, piano. No 5. Op. 102 no 2. Ré majeur.",
        "Sonates. Violoncelle, piano. No 5. Op. 102 no 2. Ré majeur.",
        "Sonatine à l'usage des enfants:pour piano",
        "Sonatine en Ré mineur:pour violon (ou flûte) et guitare",
        "Sonatine:pour alto et violoncelle",
        "Sonatine:pour violoncelle et piano",
        "Sonetto del Petrarca, n° 104. piano. S 161. N° 5.",
        "Sonetto del Petrarca, n° 123. piano. S 161. N° 6.",
        "Sonetto del Petrarca, n° 47. piano. S 161. N° 4.",
        "Stabat Mater",
        "Stabat Mater",
        "Stabat mater:pour contralto, cordes et basse continue : réduction pour piano",
        "Stabat Mater.",
        "Stabat Mater. RV 621.",
        "Suessdorf,Karl .",
        "Suite de l'Opéra-Ballet 'Mlada':pour orchestre",
        "Suite en Fa Majeur:pour deux flûtes à bec alto et une flûte à bec ténor ou d'autres instruments et basse continue",
        "Suite en fa majeur:pour deux flûtes à bec alto et une flûte à bec ténor, ou autres instruments et basse continue",
        "Suite en La Majeur, Op.6, No.1:pour flûte traversière ou pardessus de viole et basse continue",
        "Suite pittoresque:pour clarinette et cor de basset",
        "Suite pour clavecin no 2 en si bémol majeur, HWV 427",
        "Suite pour clavecin no 3 en ré mineur, HWV 428",
        "Suite pour clavecin no 8 en fa mineur, HWV 433",
        "Suite pour violoncelle seul no 1",
        "Suite pour violoncelle seul no 2",
        "Suite pour violoncelle seul no 3",
        "Suite pour violoncelle seul no 4",
        "Suite pour violoncelle seul no 5",
        "Suite pour violoncelle seul no 6",
        "Suite, Marche Joyeurse:pour deux pianos",
        "Suite:pour clarinette basse o clarinette (en sib) seule",
        "Suite:pour flûte à bec et violon",
        "Suite:pour orchestre à cordes",
        "Suite:pour violon et saxophone (ou clarinette) ou alto",
        "Suite:pour xylophone et piano",
        "Suites. Clavecin. No 2. HWV 427. Fa majeur.",
        "Suites. Clavecin. No 3. HWV 428. Ré mineur.",
        "Suites. Clavecin. No 8. HWV 433. Fa mineur.",
        "Suites. Violoncelle. no 1. BWV 1007. Sol majeur.",
        "Suites. Violoncelle. no 2. BWV 1008. Ré mineur.",
        "Suites. Violoncelle. no 2. BWV 1008. Ré mineur.",
        "Suites. Violoncelle. no 4. BWV 1010. Mi bémol majeur.",
        "Suites. Violoncelle. no 5. BWV 1011. Ut mineur.",
        "Suites. Violoncelle. no 6. BWV 1012. Ré majeur.",
        "Summertime",
        "Summertime.",
        "Sur le fleuve:pour voix, cor (ou violoncelle) et piano",
        "Sur le même accord, 'Nocturne pour violon et orchestre'",
        "Sur le même accord. Violon, orchestre.[(Nocturne)]",
        "Sur un sentier recouvert",
        "Symbiose:pour violon et contrebasse",
        "Symphonie en ré majeur",
        "Symphonie espagnole",
        "Symphonie no 1",
        "Symphonie no 1 'Rêves d'hiver'",
        "Symphonie no 1 en ré majeur, op. 25 'Classique'",
        "Symphonie no 100 'Militaire'",
        "Symphonie no 103 'Roulement de timbales'",
        "Symphonie no 11 'L'année 1905'",
        "Symphonie no 13 'Babi jar'",
        "Symphonie no 2",
        "Symphonie no 2 'Petite Russienne'",
        "Symphonie no 3 'chant de la nuit'",
        "Symphonie no 3 'des chants plaintifs'",
        "Symphonie no 3 'Divin poème'",
        "Symphonie no 6 en fa majeur, op. 68 'Pastorale'",
        "Symphonie no 6 en fa majeur, op. 68 'Pastorale'",
        "Symphonie no 7 en la majeur, op. 92",
        "Symphonie no 82 'L'ours'",
        "Symphonie No. 3, en Do mineur,:pour orchestre",
        "Symphonie No.1, op.13, en Sol mineur:'Rêve d'hiver'",
        "Symphonie No.1, op.13, en Sol mineur:'Rêve d'hiver'",
        "Symphonie No.2, op.17, en Do mineur:'Petite russe'",
        "Symphonie No.3 Opus 36:Symphonie des chants de deuil, pour soprano solo et orchestre",
        "Symphonies d'instruments à vent",
        "Symphonies d'instruments à vent.",
        "Symphonies. H 663. Ré majeur.",
        "Symphonies. N° 100. Hob I : 100. Militaire.",
        "Symphonies. N° 6. Op. 68. Pastorale.",
        "Symphonies. no 1. Op. 13. Rêves d'hiver.",
        "Symphonies. No 1. Op. 25.",
        "Symphonies. no 1. Op. 39. Mi mineur.",
        "Symphonies. no 103. Hob. I : 103. Mi bémol majeur. Roulement de timbales.",
        "Symphonies. no 2. Op. 17. Ut mineur. Petite Russienne.",
        "Symphonies. no 2. Op. 43. Ré majeur.",
        "Symphonies. No 3. Op. 36. des chants plaintifs.",
        "Symphonies. no 3. Op. 43. Do mineur. Divin Poème.",
        "Symphonies. no 82. Hob. I : 82. Do majeur. L'ours.",
        "Symphonies. Ténor, choeur et orchestre. no 3. Op. 27.",
        "Syrinx",
        "Syrinx. FL 137.",
        "Tableaux d'hiver, sonate n°2:pour basson solo",
        "Tant elle est belle:pour 4 voix ou instruments",
        "The fairy queen",
        "The Fairy Queen. Z 629.[(Opéra)]",
        "The king shall rejoice",
        "The king shall rejoice. HWV 260.",
        "The little nigar. Piano. FL 122.",
        "The Long Christmas Dinner",
        "The Ragtime Dance",
        "The Ragtime Dance",
        "The Ragtime Dance",
        "The Ragtime Dance.[(1899)]",
        "The Ragtime Dance.[(1899)]",
        "The Ragtime Dance.[(1899)]",
        "Thème et variations:pour quatuor à cordes",
        "Tierkreis",
        "Tierkreis",
        "Tierkreis. Werk Nr 41.",
        "Tierkreis. Werk Nr 41.",
        "Till Eulenspiegels lustige Streiche. TrV 171. Op. 28.",
        "Till l'espiègle",
        "Till l'espiègle:Poème symphonique",
        "Toccata pour clavecin en mi mineur",
        "Toccatas. Clavier. BWV 914. Mi mineur.",
        "Toile d'araignée:pour accordéon solo et orchestre",
        "Tränen der Musen. Klarinette, Violine, Klavier.",
        "Transcription de préludes de choral de Jean-Sébastien Bach",
        "Transcription pour piano des symphonies de Beethoven",
        "Transcriptions, volume II:pour piano solo",
        "Transcriptions, volume III:pour piano solo",
        "Transcriptions, volume VII:pour piano solo",
        "Träumerei. No 7. Op. 15. Fa majeur.",
        "Träumerei. No 7. Op. 15. Fa majeur.",
        "Treize pièces Op. 47:pour deux clarinettes et alto ou trois clarinettes",
        "Trente-six valses, op. 9, D 365",
        "Trio (Trio pour enfants) en ré majeur op. 39 Nr. 2:pour violon, violoncelle et piano",
        "Trio (Trio pour enfants) en sol majeur op. 35 Nr. 2:pour violon, violoncelle et piano",
        "Trio à cordes",
        "Trio à cordes:pour violon, alto et violoncelle",
        "Trio concertant en Ré Majeur:pour 2 violes de gambe et basse continue.",
        "Trio concertant en Sol Majeur:pour 2 violes de gambe et basse continue.",
        "Trio élégiaque no 1",
        "Trio en Do Majeur:pour clavecin obligé, viole de gambe et basse continue.",
        "Trio en do majeur:pour deux flûtes (ou violons) et guitare",
        "Trio en Do mineur:pour clarinette, cor et piano",
        "Trio en Fa Majeur (BWV 1040):pour violon, hautbois et basse continue",
        "Trio en Fa Majeur:pour viole de gambe, clavecin obligé et basse continue.",
        "Trio en mi bémol majeur Op. 20 N°.2:pour deux clarinettes et basson",
        "Trio en mib majeur:pour violon, violoncelle (alto, cor) et piano, d'après le quintet pour cor, violon, deux altos et violoncelle",
        "Trio en Ré Majeur:pour cor, violon et basse continue",
        "Trio en Ré mineur Op.3:pour clarinette (ou violon), violoncelle et piano",
        "Trio en Sol mineur (Elégiaque N°1):pour violon, violoncelle et piano",
        "Trio en sol mineur op. 63",
        "Trio en sol mineur Op. 63:pour piano, flûte (violon) et violoncelle",
        "Trio facile op. 32:pour violon, alto et piano",
        "Trio pour clarinette en Sib, violoncelle et piano:Un vendredi soir en août",
        "Trio pour piano et cordes no 1",
        "Trio pour piano et cordes no 1, op. 8",
        "Trio pour piano et cordes no 2",
        "Trio pour piano et cordes no 3",
        "Trio pour piano et cordes no 4 'Gassenhauer-Trio'",
        "Trio pour piano et cordes no 4 'Gassenhauer-Trio'",
        "Trio pour piano et cordes no 5 'Trio des esprits'",
        "Trio pour piano et cordes no 6",
        "Trio pour piano et cordes no 7 'A l'Archiduc'",
        "Trio pour piano, clarinette et violon",
        "Trio pour piano, clarinette et violon",
        "Trio:pour clarinette, violon et piano",
        "Trio:pour clarinette, violon et piano",
        "Trio:pour deux trompettes et trombone",
        "Trio:pour flûte, clarinette et basson",
        "Trio:pour flûte, violoncelle et piano",
        "Trios avec piano livre III:Trios avec flûte",
        "Trios avec piano:Volume I",
        "Trios avec piano:volume II",
        "Trios élégiaques. Piano, cordes. No 1. Sol mineur.",
        "Trios:pour deux violons et violoncelle",
        "Trios. Flûte ou violon, violoncelle, piano. J 259. Sol mineur.",
        "Trios. Piano, clarinette, violon.",
        "Trios. Piano, clarinette, violon.",
        "Trios. Piano, clarinette, violoncelle. No 4. Op. 11. Si bémol majeur.",
        "Trios. Piano, cordes. N° 1. Op. 8.",
        "Trios. Violon, violoncelle, Piano. No 1. Op. 1. Mi bémol majeur.",
        "Trios. Violon, violoncelle, Piano. No 2. Op. 1. Sol majeur.",
        "Trios. Violon, violoncelle, Piano. No 3. Op. 1. Do mineur.",
        "Trios. Violon, violoncelle, piano. No 4. Op. 11. Si bémol majeur.",
        "Trios. Violon, violoncelle, piano. No 4. Op. 11. Si bémol majeur.",
        "Trios. Violon, violoncelle, piano. No 5. Op. 70 no 1. Ré majeur. Geister-Trio.",
        "Trios. Violon, violoncelle, piano. No 6. Op. 70 no 2. Mi bémol majeur.",
        "Trios. Violon, violoncelle, piano. No 7. Op. 97. Si bémol majeur. A l'Archiduc.",
        "Trois chansons:pour baryton, clarinette, alto et violoncelle, sur des textes d'Arthur Rimbaud, traduits en tchèque",
        "Trois danses latinoamericaines:pour piano",
        "Trois duos concertants:pour flûte et alto",
        "Trois duos, op. 68:pour violon et alto",
        "Trois duos:pour clarinette en sib et basson",
        "Trois Duos:pour flûte et violoncelle",
        "Trois duos:pour violon et alto",
        "Trois Duos:pour violon et violoncelle",
        "Trois écossaises",
        "Trois études de concert:pour percussion solo",
        "Trois études:pour piano à six mains",
        "Trois mazurkas Op.59",
        "Trois miniatures brésiliennes:pour percussion",
        "Trois paraphrases de danses:pour flûte, alto et cor en Fa",
        "Trois pièces:pour trois instruments SAT (Soprano, Alto, Ténor)",
        "Trois quatuors:pour clarinette, violon, alto et violoncelle",
        "Trois ragtimes:pour flûte à bec alto et guitare",
        "Trois romances Op. 21",
        "Trois sambas folles:pour violon et violoncelle ou deux violoncelles",
        "Trois Sonates en trio opus 5, nos 6, 3 et 2:pour deux violons et basse continue",
        "Trois sonates pour viole de gambe et clavier (clavecin):Version pour alto et clavier (piano ou clavecin)",
        "Trois sonatines:pour flûte à bec soprano et basse",
        "Trois sonnets de Pétrarque:pour piano",
        "Trois trios:pour deux hautbois et basson",
        "Trois valses Op.64",
        "Troisième ouverture de concert:Mer calme et voyage prospère",
        "Troisième sonate en La Majeur:pour violon, viole de gambe (ou 2e. violon) et basse continue",
        "Troisième voix pour l'Invention à 2 voix en Ré mineur BWV 775 de J.-S. Bach:conducteur pour distrubution instrumentale variable (trois parties) au choix",
        "Un soir au village:pour flûte et piano",
        "Une suite sur 'La chauve souris':pour quatuor de vents (hautbois, clarinette, horn et basson)",
        "Une vie de héros",
        "Une vie de héros",
        "Ungarische Tanze. Piano à quatre mains. No 5. WoO1. Fa dièse mineur.",
        "Ungarische Tanze. Piano à quatre mains. No 5. WoO1. Fa dièse mineur.",
        "Ungarische Tanze. Piano à quatre mains. No 6. WoO1. Ré bémol majeur.",
        "Ungarische Tanze. Piano à quatre mains. No 6. WoO1. Ré bémol majeur.",
        "Union mystique:pour flûte et guitare",
        "V mlhach. Piano. JW VIII/22.",
        "V srednej Azii.",
        "Valse impromptu",
        "Valse impromptu. Piano. S 213.",
        "Valse triste. Op. 44 no 1.",
        "Valse triste. Op. 44 no 1.",
        "Valses oubliées",
        "Valses oubliées. Piano. S 215.",
        "Valses sentimentales, D 779",
        "Valses sentimentales, D 779",
        "Valses sentimentales. Piano. D 779. Op. 50.",
        "Valses sentimentales. Piano. D 779. Op. 50.",
        "Valses. Piano. no 7. CT 213. Op. 64 no 2. Do dièse mineur.",
        "Variantes:Musique pour violon solo, cordes et bois",
        "Varianti",
        "Varianti.",
        "Variationen über das Motiv von Bach 'Weinen, Klagen, Sorgen, Zagen' und des Crucifixus der H-moll Messe. Piano. S 180.",
        "Variations sur 'Là ci darem la mano' d'après 'Don Giovanni' de Mozart WoO 28:pour deux hautbois et cor anglais",
        "Variations sur 'Weinen, Klagen, Sorgen, Zagen' de Jean-Sébastien Bach",
        "Variations sur l'hymne 'Gott erhalte':version originale pour piano",
        "Variations sur la marche nuptiale de Mendelssohn:pour quatuor à cordes",
        "Variations sur un chant folklorique du Luxembourg:pour flûtes à bec (soprano, alto et ténor)",
        "Vec Makropulos. JW I/10.[(Opéra)]",
        "Venuskränzlein:Introductions, Gaillardes et Canzones à 5 et 6 parties (flûtes à bec, violes ou autres instruments)",
        "Via crucis",
        "Via crucis. Piano. S 504a.",
        "Vieilles danses hongroises du 17e siècle:pour flûte et piano",
        "Vier norwegische Tänze. piano à quatre mains. Op. 35.",
        "Vier Tondichtungen nach Arnold Böcklin. op. 128.",
        "Vierter Mephisto Walzer. Piano. S 696.",
        "Vieux airs de danse viennois:pour quatuor à cordes",
        "Vingt et une danses hongroises pour piano à quatre mains, WoO 1",
        "Vingt et une danses hongroises pour piano à quatre mains, WoO 1",
        "Vingt et une danses hongroises pour piano à quatre mains, WoO 1",
        "Vingt noëls polonais pour choeur à l'unisson et orchestre:réduction pour choeur à l'unisson et piano",
        "Violin concerto '1001 Nights in the Harem'.",
        "Vol de nuit",
        "Vol de nuit:opéra en un acte d'après Saint-Expupéry ; nouvelle traduction en allemand",
        "Volo di notte.[(Opéra)]",
        "Volsebnoe ozero. Orchestre. Op. 62.",
        "Von der Wiege bis zum Grabe. S 107.",
        "Water music",
        "Water music. HWV 348-350.",
        "Weihnachtsbaum. Piano. S 186.",
        "Weinen, Klagen, Sorgen, Zagen, BWV 12",
        "When the Saints Go Marching In",
        "When the saints go marching in.",
        "Winterreise. D 911. Op. 89.[(lieder)]",
        "Winterreise. D 911. Op. 89.[(lieder)]",
        "Winterreise. D 911. Op. 89.[(lieder)]",
        "Z mrtvého domu. JW I/11.[(Opéra)]",
        "Zwei Gefühle.",
        "Zwölf Walzer, siebzehn Ländler und neun Ecossaisen. piano. D 145. Op. 18.",
        "Zwölf Walzer, siebzehn Ländler und neun Ecossaisen. piano. D 145. Op. 18.",
    ]
}
