work_names = {
    "_": [
        "Starmania",
        "sacre du Printemps",
        "Sacre du printemps",
        "14e quatuor",
        "l’ouverture de Don Giovanni",
        "flûte enchantée",
        "flute enchantée",
        "Symphonie fantastique",
        "traviata",
        "Traviata",
        "5e Symphonie",
        "la 5eme symphonie",
        "5eme symphonie",
        "Symphonie n5",
        "symphonie n°5",
        "symphonie n°5",
        "1ere symphonie",
        "1ere symphonie",
        "la ballade des gens heureux",
        "Je t'aime, moi non plus",
        "la Lettre à Élise",
        "Lettre à Élise",
        "Parsifal"
        "le Parsifal"
        "à la cime d’un grand arbre",
        "les Nocturnes",
        "Hey Jude",
        "la pub CN",
        "Chevauchée des Valkyries",
        "Marche Impériale",
        "Marche Impériale",
        "tireli",
        "9e Symphonie",
        "9eme Symphonie",
        "symphonie n° 9",
        "symphonie n°9",
        "symphonie n9",
        "la Symphonie no 40",
        "Purple Rain",
        "Symphonie inachevée",
        "sonate pour piano n11",
        "Donna e mobile",
        "générique de Colargol",
        "l'ageasse a fait son nid",
        "concerto pour piano 16",
        "requiem",
        "Wonderwall",
        "symphonie no 1",
        "Nocturnes, opus 9",
        "Études",
        "la Symphonie no 6",
        "la symphonie no 8",
        "Concertos brandebourgeois",
        "ave maria",
        "Fugue en sol mineur",
    ]
}